### ISSUE TITLE
Kernel Restarting

### ISSUE THREAD

**Issue by ssmssdiop** [networkit/networkit#1010]
I try to use networkit. But when I calculate the betweenness it gives me an error **Kernel Restarting
The kernel of Documents/robustes_betweenness.ipynb seems to be dead. It will restart automatically**.

Here is the code
`import networkx as nx`
`import networkit as nk`
`karate = nx.karate_club_graph()
k_it = nk.nxadapter.nx2nk(karate)
bet_it = nk.centrality.DegreeCentrality(k_it).run()`

I am using a macBook pro M1 2021. 
The version of networKit is 10.0
The version of networkx is 2.8.4
The version of python is 3.9.13

**Comment by fabratu** [comment]
Unfortunately I am not able to reproduce the error (using different Python and networkx versions). Here is one example:

```
import networkx as nx
import networkit as nk

karate = nx.karate_club_graph()
k_it = nk.nxadapter.nx2nk(karate)
print(k_it)
>> NetworKit.Graph(n=34, m=78)

bet_it = nk.centrality.DegreeCentrality(k_it).run()
print(bet_it.scores())
>>[16.0, 9.0, 10.0, 6.0, 3.0, 4.0, 4.0, 4.0, 5.0, 2.0, 3.0, 1.0, 2.0, 5.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 5.0, 3.0, 3.0, 2.0, 4.0, 3.0, 4.0, 4.0, 6.0, 12.0, 17.0]

print(nk.__version__)
print(nx.__version__)
>>10.0
>>2.8.5
```

**Comment by ssmssdiop** [comment]
Thanks. Jupyter restart the kernel when I execute, for example the DegreeCentrality() method. I will reinstall anaconda.

**Comment by ssmssdiop** [comment]
The problem is fixed. I install networkit with conda.
