### ISSUE TITLE
Question: Release schedule

### ISSUE THREAD

**Issue by Thijss** [networkit/networkit#1014]
Is there a release schedule for networkit?

I am specifically waiting for a release that includes https://github.com/networkit/networkit/pull/1000, so that the 3.11 binaries are available on pypi

**Comment by fabratu** [comment]
There is a new release scheduled for this year, likely in 1-2 weeks (depending on still open PRs). We also have to fix an issue with the most recent MSVC compiler.

In case thats not clear, as a workaround you can also download the 3.11 binaries from the github actions build from master (links are valid for 30 days). Example: https://github.com/networkit/networkit/actions/runs/3486697180

**Comment by Thijss** [comment]
Any updates on the next release?

**Comment by fabratu** [comment]
Sry for the delay. The release is now scheduled for the upcoming week. We like to include one more feature (support of directed graphs for `node2vec`) for the release.
