### ISSUE TITLE
Wrong type of parameter

### ISSUE THREAD

**Issue by destiny1009** [networkit/networkit#1023]
In [43]: nk.community.NMIDistance.getDissimilarity(G, communities, communities)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[43], line 1
----> 1 nk.community.NMIDistance.getDissimilarity(G, communities, communities)

TypeError: descriptor 'getDissimilarity' for 'networkit.community.NMIDistance' objects doesn't apply to a 'networkit.graph.Graph' object

In [44]: G
Out[44]: <networkit.graph.Graph at 0x270339e7b40>

In [45]: communities
Out[45]: <networkit.structures.Partition at 0x27075130870>

Only the methods of this class（networkit.community.DissimilarityMeasure） are unable to recognize this parameter type, the rest of the quality indicators can be recognized and calculated。

About G and communities are generated according to the sample code

**Comment by destiny1009** [comment]
Could it be because I have something less installed? Or did I misunderstand its usage?

**Comment by fabratu** [comment]
It's only a minor typo. Use `nk.community.NMIDistance().getDissimilarity(...)`. 

Working example:
```
G = nk.generators.BarabasiAlbertGenerator(10,1000).generate()
par1 = nk.community.PLM(G).run().getPartition()
par2 = nk.community.PLP(G).run().getPartition()
print(nk.community.NMIDistance().getDissimilarity(G, par1, par2))
```

**Comment by destiny1009** [comment]
Your case is executable, but I still can't understand why my previous code produces a type mismatch. The parameter types are identical to those in your sample.

**Comment by destiny1009** [comment]
thank you

**Comment by destiny1009** [comment]
thank you
