### ISSUE TITLE
Difference between Adamic-Adar Distance and Index?

### ISSUE THREAD

**Issue by j-adamczyk** [networkit/networkit#1026]
What exactly is the difference between Adamic-Adar Distance and Index? They give quite similar, but visibly different results.

Am I right that `AAD = 1 / AAI`, i.e. Adamic-Adar Index is a similarity (higher = more similar), whereas Adamic-Adar Distance is a metric (higher = more dissimilar)?

**Comment by fabratu** [comment]
Correct me if I am wrong, but I think we covered this in #1025. The formula is a bit different, however the meaning is correct.

Will close this issue for now. Feel free to reopen it, if there are any additional questions.

**Comment by j-adamczyk** [comment]
@fabratu you're right. But if this is more general, i.e. each distance is just an inverse index, in a sense, then this should be stated in the documentation. At least I could not find anything about such definition for any class.
