### ISSUE TITLE
Citation for NeighborhoodDistanceIndex?

### ISSUE THREAD

**Issue by j-adamczyk** [networkit/networkit#1027]
As far as I understand, Neighborhood Distance Index for an edge is just the overlap of neighborhoods divided by square root of node degrees. Is there a citation or source for this measure, or is it strictly Networkit-specific invention?

**Comment by j-adamczyk** [comment]
I think that this is a weird name for Salton's cosine index. Am I right? If so, I think that proper name and reference should be added.

**Comment by clstaudt** [comment]
[Our student's 2015 Bachelor's thesis](http://parco.iti.kit.edu/attachments/Kolja%20Esders%20-%20Thesis.pdf) claims invention in the context of link prediction

> We also introduce a new local index called Neighborhood Distance. The experiments show that supervised methods consistently outperform unsupervised methods by up to 7.2% with respect to the ROC metric. 

and cites as inspiration

> This index was used by Wu et al. [62] to address the hop- distance ambiguity in range-free localization for wireless ad hoc and sensor networks

who have coined

> a new measure, called regulated neighborhood distance (RND), to address this problem by relating the proximity of two neighbors to their neighbor parti- tions.

-- https://sci-hub.se/10.1016/j.comnet.2012.07.007

Probably a case of straightforward things getting frequently reinvented...

**Comment by j-adamczyk** [comment]
@clstaudt thank you.
