### ISSUE TITLE
Creating Layout for a graph using Fruchterman Reingold Algo

### ISSUE THREAD

**Issue by ahmedrshdy** [networkit/networkit#1056]
Hi,

I am a bit newbie in field of Graph Analysis. Previously I was using igraph for detecting communities and generating layouts for small and medium graphs. When the graphs I am working on get bigger, I had found igraph is totally useless, this is how I discovered Networkit.

Successfully I am able to detect communities for a big graph with 3.5m nodes and 11m edges. Also I was able to generate page ranks for all nodes, speed was amazing, even thought something is wrong :)

Anyway, now I am stuck with generating the layout for the graph so I can plot it on web based tool we have, unfortunately the documentation does not cover that part. I used to use Fruchterman Reingold within igraph but could not find similar utility within Networkit.

Any advises?

Ahmed

**Comment by clstaudt** [comment]
> a big graph with 3.5m nodes and 11m edges

What would you expect to see in a 2D-plot of the entire graph?

**Comment by szhorvat** [comment]
> When the graphs I am working on get bigger, I had found igraph is totally useless

If you see specific issues with igraph, please file a bug report.

Note that there are several very different methods for both community detection and layout computations. You did not mention which methods you tried using igraph, and using NetworKit. For very large graphs, only linear-time methods will be feasible.

The Fruchterman-Reingold method has quadratic complexity in the number of vertices (pairwise forces need to be computed), so it won't work for very large graphs. But as said by @clstaudt, even if it did, it's simply not possible to draw so many vertices and edges in a useful way ...

**Comment by ahmedrshdy** [comment]
@szhorvat  

Thanks for the response, currently I am using Netowkit as it is much faster in large networks. When I was using igraph, community detection never converged after many hours no matter the computing power I provide. In contrast, NetworKit is able to detect communities in less than a minute

@clstaudt 
I do not plan to plot the graph in Jupyter, instead want to generate the layout coordinates for each node so as to pass it to [SigmaJS](https://www.sigmajs.org/) library

**Comment by ahmedrshdy** [comment]
@hmeyerhenke that also work, would you please advise which notebook exactly

**Comment by hmeyerhenke** [comment]
@fabratu : we used to have a notebook to show how the interaction with gephi works. Where can it be found?

**Comment by ahmedrshdy** [comment]
thanks @hmeyerhenke  @fabratu  for your help
