### ISSUE TITLE
Error when calling networkit.plot.coreDecompositionSequence(G)

### ISSUE THREAD

**Issue by Fabio-Giacomelli** [networkit/networkit#1098]
... line 125, in coreDecompositionSequence
    shells = centrality.CoreDecomposition(G).run().shells()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'networkit.centrality.CoreDecomposition' object has no attribute 'shells'

**Comment by fabratu** [comment]
Hi,

thanks for posting the issue!

@PetholzA Can you look into this issue and also add tests for the module?

**Comment by fabratu** [comment]
Will close this issue. It is fixed in #1099 and will be part of future releases.
