### ISSUE TITLE
setWeight() api 

### ISSUE THREAD

**Issue by Ty-creater** [networkit/networkit#1143]
G = nk.Graph(directed=True, weighted=True)
 min_weight = 0
    max_weight = 0
    with open(graph_path, 'r') as file:
        for line in file:
            if line.startswith('%') or line.startswith('#'): continue
            data = line.strip().split()
            from_node = int(data[0])
            to_node = int(data[1])
            weight = round(float(data[2]), 4)
            if weight > max_weight:
                max_weight = weight
            elif weight < min_weight:
                min_weight = weight
            G.addEdge(from_node-1, to_node-1, weight, addMissing=True)
            G.addEdge(to_node-1, from_node-1, weight)
    
for edge in G.iterEdgesWeights():
        from_node, to_node, weight = edge
        new_weight = (weight - min_weight) / (max_weight - min_weight)
        G.setWeight(from_node, to_node, new_weight)
        
 The weights of the dataset are positive and negative, and I want to normalize them, but when I change the weights of the edges, there is still a small part of the edge weights that are not modified

**Comment by fabratu** [comment]
Hi,

can you give an example from your data, where a weight is not correctly updated?

**Comment by Ty-creater** [comment]
The dataset is available at this URL：http://konect.cc/networks/wikiconflict/

**Comment by fabratu** [comment]
Based on the description of the dataset, it contains (amongst other edge specific data) multi-edges. Note that NetworKit does not support multiple edges consistently (also see documentation of `addEdge`[1]). It is likely, that those edges are missing from your normalization, which are multi-edges. 

If you only care about having a "complete" data structure, `G.forEdges()` should work for normalizing the weight[2]. However, most algorithms will also not give consistent results for multi-edges. I suggest to "sanitize" the graph after reading by calling `G.removeMultiEdges()`.

[1] https://networkit.github.io/dev-docs/python_api/networkit.html?highlight=addedge#networkit.Graph.addEdge
[2] https://networkit.github.io/dev-docs/notebooks/GraphNotebook.html

**Comment by Ty-creater** [comment]
I'm not reading this native dataset directly, but it's been processed and the duplicate edges have been removed.

**Comment by Ty-creater** [comment]
You can see the debugging results I provided：https://pic.imgdb.cn/item/654899b8c458853aef71d039.png

**Comment by Ty-creater** [comment]
Sorry, I looked closely at my treatment of duplicate edges retaining duplicate edges with different weights. You're right, and I'm very sorry for the interruption.

**Comment by fabratu** [comment]
No problem at all - will close this issue.
