### ISSUE TITLE
Add wheels for python 3.12

### ISSUE THREAD

**Issue by Thijss** [networkit/networkit#1144]
Python 3.12 is out :) 

Would be nice to add wheels for this version too

**Comment by Thijss** [comment]
I can prepare a draft PR for this as soon as I find time

**Comment by treykeown** [comment]
See #1150 - seems to have trouble building for 3.12

**Comment by fabratu** [comment]
Hi,

thanks for posting this (and #1150) We are currently fixing the Python 3.12 issues and also add wheels once they are fixed. It's likely, that the pins in `pyproject.toml` creates problems here. They were introduced for `Cython 3.0.0` release. The older `setuptools` is still using the deprecated (and in Python `3.12` removed) API from `pkgutil`.

It seems to work for Python 3.12 to remove the pins. Currently testing this fix for older versions of Python locally.

**Comment by fabratu** [comment]
The issue is fixed in #1151. Closing this for now.

**Comment by pbregener** [comment]
Hi @fabratu,
Am I doing something wrong or are the wheels just not uploaded, yet? Would that require tagging a new release?

**Comment by fabratu** [comment]
No they are not, but I can manually upload them. Will try to do that in the upcoming days.

**Comment by Thijss** [comment]
@fabratu any updates on the new release?
Also, the release frequency now seems about once a year. I wonder what is holding back more frequent releases?

**Comment by fabratu** [comment]
Most of the time there is a PR holding back the release, this time it is the support of certain compilers (see #1159). Once I have found the time to fix this, the release is done. So a more general answer to your question would be: resource constraints.

In general, I would like to release more often - or, even better, restructure how releases are done.
