### ISSUE TITLE
g++ version

### ISSUE THREAD

**Issue by fixikmila** [networkit/networkit#1148]
Hello. It doesn't work with g++ 13. I have errors like "error: 'uint64_t' was not declared in this scope."
And when i changed g++ to g++ 12 in cmakelists, the errors disappeared.

**Comment by fabratu** [comment]
Hi, thanks for raising the issue. We still test against gcc in our CI-builds.

@PetholzA Can you look into this issue?

**Comment by fabratu** [comment]
Fixed with #1159. 

Closing this issue. You are welcome to reopen it, if there is another problem.
