### ISSUE TITLE
addEdges does not exist for Python

### ISSUE THREAD

**Issue by cheginit** [networkit/networkit#1152]
In the [documentation](https://networkit.github.io/dev-docs/python_api/graph.html?highlight=addedges#networkit.graph.Graph.addEdges) `Graph.addEdges` function exists but when I try to use it, I get this error `AttributeError: 'networkit.graph.Graph' object has no attribute 'addEdges'`:

```python
import networkit as nk

edge_list = [(0, 1, 0.1), (1, 2, 0.3)]
g = nk.Graph(weighted=True, directed=False, edgesIndexed=True)
_ = g.addNodes(3)
_ = g.addEdges(edge_list)
```

This works:

```python
_ = [g.addEdge(u, v, w) for u, v, w in edge_list]
```

**Comment by fabratu** [comment]
Hi,

the documentation is currently built against the master branch. Therefore, it includes functionality, which is not yet part of any release. I suppose you used any release version of NetworKit (like 10.1)? 

If so, you can either build the most recent version yourself (following the readme) or use a pre-built wheel from the CI (for example here: https://github.com/networkit/networkit/actions/runs/7004494307).

**Comment by cheginit** [comment]
Ah. I see. Right, I am using the latest version on conda-forge. Considering that the last release was in April, I think it would be great to have a versioned website. Thanks for the great work!
