### ISSUE TITLE
widgetFromGraph: 2d plotly draws edges that do not exist

### ISSUE THREAD

**Issue by bernlu** [networkit/networkit#1204]
example:
```py
G = nk.Graph(5, True)
G.addEdge(0,1)
G.addEdge(1,2)
G.addEdge(0,4)
G.addEdge(1,3)

nk.vizbridges.widgetFromGraph(G, dimension=Dimension.TwoForcePlotly)
```

Results in a figure with five edges, but `G` only has four.
![image](https://github.com/networkit/networkit/assets/85391740/577245a8-81bb-4086-95d5-1605d79a9586)

**Comment by fabratu** [comment]
Fixed in #1160 - closing this issue for now.
