### ISSUE TITLE
GraphTools.topologicalSort() assumes input graph is compacted 

### ISSUE THREAD

**Issue by jurepustos** [networkit/networkit#1224]
I've been pulling my hair out over `GraphTools.topologicalSort()` for about two days, before looking into the source code and noticing that the algorithm actually assumes that node id's go from 0 to number of nodes - 1. The documentation does not mention this and I feel that it should explicitly mention such a restriction. The library could also give a way to pass a node id map to the function if the graph is not compacted.
I plan on making a pull request with a solution in the relative near future, but I want this issue/restriction to be known.

**Comment by fabratu** [comment]
Hi,

yes , thank you - that's correct. We should name the restriction in the documentation. If you need any help in creating a PR for adding (or/and adding a node map), feel free to ask.

**Comment by jurepustos** [comment]
closing since #1241 fixed this issue a while ago
