### ISSUE TITLE
Global Curveball on bipartite graph

### ISSUE THREAD

**Issue by minkim88** [networkit/networkit#1238]
I've been working on a project where I need to randomize a very large bipartite network. I found Global Curveball function to be very efficient, but can't find a way to apply this function to a bipartite network. Is there a way I can do this?

Thanks!

**Comment by fabratu** [comment]
Hi,

in order to clarify your question. You want to randomize the neighborhood of a given bipartite graph and the result should still be a bipartite graph? If that's the case, our global curveball algorithm does not support this.

**Comment by minkim88** [comment]
That is exactly the case I need. I guess I'll need to find out another way.

Thanks for the quick response!
