### ISSUE TITLE
Different local degree sparsification scores on a symmetric graph

### ISSUE THREAD

**Issue by StefanoCretti** [networkit/networkit#1242]
When using LocalDegreeScore on a small symmetric graph, I would expect the scores of all edges to be identical, though that does not appear to be the case. It might just be that I am getting the algorithm wrong, since even after reading https://github.com/networkit/networkit/issues/1028#issue-1553521146 and the paper I am not 100% sure about it.

**Environment**: conda 23.7.4, in a fresh environment `conda install networkit` (11.0) and `conda install pandas`.
**Code**: 
```
import networkit as nk

G = nk.Graph(3, weighted=False, directed=False)
G.addEdge(0, 1)
G.addEdge(0, 2)
G.addEdge(1, 2)
G.indexEdges()

lds = nk.sparsification.LocalDegreeScore(G)
lds.run()
print(lds.scores())
``` 
Prints
`[1.0, 1.0, 0.0]`

To my understanding the scores should all be 1, since every single score should be given by

$l_c(u, v):= 1 - \log(r_c(u,v))/\log(d(u)) = 1 - \log(1)/\log(2) = 1$

Since:
- $r_c(u,v)$ will always be 1 due to being a tie between all neighbors
- $d(u)$ will always be 2 by definition

Any help in understanding this would be much appreciated, thanks.

**Comment by Zsstarry** [comment]
Regarding this issue, my explanation is that:

Suppose three nodes, A, B, C of the same degree of 2 in forming a triangle.

For A, the ranking score r_c(A,B) and r_c(A,C) are different, though B and C are of the same degree.
When ranking B and C based on their degrees, we have either r_c(A,B)=1 and r_c(A,C)=2, or r_c(A,B)=2 and r_c(A,C)=1.
Therefore, l_c(A,B)=1 and l_c(A,C)=0, or l_c(A,B)=0 and l_c(A,C)=1.
But, to eventually determine the final local edge score of (A,B), we need to see max{l_c(A,B), l_c(B,A)}.
l_c(A,B) is from the perspective of A, while l_c(B,A) is that of B.
Therefore, there can be four possibilities: max{l_c(A,B)=1, l_c(B,A)=1}=1, max{l_c(A,B)=0, l_c(B,A)=1}=1, max{l_c(A,B)=1, l_c(B,A)=0}=1, and max{l_c(A,B)=0, l_c(B,A)=0}=0

Therefore, having the local edge score value of "0" is indeed possible.

**Comment by StefanoCretti** [comment]
Thanks, that does indeed explain the result, though now some new questions arise:

1. From the formula in the paper, one would assume that, in case of a tie, all tied values would get the same rank. As an example (and please, correct me if I am wrong in the calculations), if the nodes in the neighborhood of some node $u$ have degrees [1,1,5,5,4], they would get ranks [1,1,4,4,3] (since the rank is the number of nodes in the neighborhood with degree lower than the considered neighborhood node + 1). Why not just keeping the tie rather than "randomly" (see point 2) splitting the tie?
2. As far as I can tell, the result does seem to be deterministic, so the ties are not split randomly. How is tie splitting defined?

**Comment by Zsstarry** [comment]
Hi, @StefanoCretti, for your two questions:
Given the example you mentioned here, my understanding from the paper is that, if the neighborhoods of $u$ are $[a,b,c,d,e]$ with degrees $[1,1,5,5,4]$, respectively, the sorted list of neighborhoods based on degrees in descending order (see Page8 of the journal paper "Structure-preserving sparsification methods for social networks") would be $[c,d,e,a,b]$.
**"Not that, if the sorting process is stable, then the sorted list of neighborhoods would definitely be fixed"**.
Therefore, the rankings of neighborhoods are $[c=1,d=2,e=3,a=4,b=5]$.
Therefore, $l_c(u,a)=1-log(r_c(u,a)=4)/log(d(u)=5)=0.14$

Of course, this is from the perspective of $u$. If we look at $a$, let's say the neighbors of $a$ are $[u,v,w]$ with degrees $[4,5,3]$. The corresponding rankings are $[2,1,3]$. Therefore, from the perspective of $c$, $l_c(a,u)=1-log(r_c(a,u)=2)/log(d(u)=3)=0.37$.

Eventually, the local edge score of the edge $\\{u, a\\}$ or $\\{a, u\\}$ is $max(0.14, 0.37)=0.37$.

Hope that this would clarify your concerns.

**Comment by StefanoCretti** [comment]
Thank you for your patience @Zsstarry, but that does only partially answer the questions.

I still do not understand **why** ties are broken and not left as is, since, in my opinion, this is a major issue for two reasons:
1. even if the sorting is stable, and thus the algorithm will always produce the same result on the very same graph, the algorithm is sensitive to node labeling/ids assignment. Rephrasing, the same graph but with node ids shuffled around will produce different results since the ranking depends on the order in which nodes are visited (as far as I can tell, they are visited in id order, therefore a node with id 3 will always be visited after node with id 2, and therefore it will always get a higher rank when the two are in the same neighborhood. The opposite would happen were their ids swapped).
2. This way the algorithm can produce disconnected components, which is one of the main things it should **NOT** do to preserve graph structure. Take as an example a chain of nodes connecting two high density regions. For a very simple representation
$X_1 - a - b - c - d - e - X_2$
where $X_1$ and $X_2$ are dense regions of the graph and $a,b,c,d,e$ are individual nodes (I know this is a bit crude but bear with me please). 
    - Let's now consider node $b$; by allowing for ties, $r_c(b,a) = r_c(b,c)= 1$, therefore $l_c(b,a) = l_c(b,c)= 1$. When not allowing for ties, one of $a$ or $c$ will be assigned rank 1, while the other 2. Let's say that $r_c(b,a) = 1$ while $r_c(b,c)= 2$; in this case $l_c(b,a) = 1$ while $l_c(b,c)=0$.
    - Let's do the same for node $c$. When allowing for ties $l_c(c,b) = l_c(c,d)= 1$. If we do not allow for ties, and say that $r_c(c,b)= 2$ while $r_c(c,d)= 1$, then $l_c(c,b)=0$ while $l_c(c,d)=1$.
    - In our example it follows that, when allowing for ties, $`l_c(\{b,c\}):=\max(1,1)=1`$, while when not allowing for ties $`l_c(\{b,c\}):=\max(0,0)=0`$
    - When allowing for ties, the edge will be kept, preserving graph structure. When not allowing for ties the edge will be lost, breaking the graph into two components.
    - If the chain is particularly long, multiple break points can occur, creating small disconnected components and even doublets. It is worth noting that this is an extreme case, but the problem is much deeper than this, since even if tie breaking does not make the edge score zero, it could cause edge removal depending on the filtering threshold used.

I would like to add that the general definition of neighborhood rank provided at page 4 of the very same paper, e.i "**Definition 3** (_Neighborhood rank_) Given a graph $G=(V,E)$ and an edge score $c: E \to \mathbb{R}^+$, the neighborhood rank $r_c(u,v)$ is the position of $v$ in the sorted list of neighbors of $u$, i.e., $`r_c(u,v):=|\{x \in N(u) : c(\{u, x\}) < c(\{u,v\})\}| + 1`$" is misleading and could easily make you think of the reverse sorting order, as I did.

**Comment by Zsstarry** [comment]
Hi, @StefanoCretti , I will start with your last question:

- "The definition is misleading ..."
Perhaps the sorting criteria need to be specified a bit.
More details, when using sparsification based on local degree, are given in the later text of that paper.

- “The same graph but with node ids shuffled around will produce different results since the ranking depends on the order in which nodes are visited”
Yes, the dependency on node ids cannot be avoided in this case. When sorting based on degrees, it is common to have nodes of the same degrees. When changing the ids of these nodes, the sorting results may differ (locally). But this does not change a lot on the graph sparsification result, because for graph sparsification, what we want to preserve is the graph properties. Besides, generating a deterministic sparsified graph is not the priority.

- "This way the algorithm can produce disconnected components, which is one of the main things it should NOT do to preserve graph structure"
For special local subgraphs, this indeed exists. There is no guarantee that the graph after sparsification will still maintain the same largest connected component. Sometimes, when maintaining the largest connected component, the other properties may not be well preserved.

**Comment by StefanoCretti** [comment]
I do believe that node ids dependency can in fact be avoided with tied ranking, and I would argue that this is not the case in which "maintaining the largest connected component, the other properties may not be well preserved", since the largest component is lost due to an approximation which could be avoided.

I do understand that the differences might be local and minimal, and that they will most likely not affect the outcome of the analysis, so this choice in justifiable, especially if it means better performance. That being said, I think that this choice might compound to make the analysis less reproducible. I would suggest adding a comment in the documentation regarding this.

Since I would rather have reproducibility over peak performance, I think I will implement my own version with ties, but thanks for the time you spent explaining and answering my questions, @Zsstarry.
