### ISSUE TITLE
Multiple class inheritance in Cython

### ISSUE THREAD

**Issue by angriman** [networkit/networkit#181]
Some NetworKit classes inherit from multiple classes like `Algorithm`, `DynAlgorithm` or `Centrality`. For example, [DynTopHarmonicCloseness](https://github.com/kit-parco/networkit/blob/5cc74b434b4891ea53a278777a3699a26bedf379/networkit/_NetworKit.pyx#L6550l) extends both `Algorithm` and `DynAlgorithm`. However, when it comes to Cython there is no easy-way to do so.

**Comment by eug93** [comment]
A very similar issue is also multiple inheritance in Cython. Classes like [DynTopHarmonicCloseness](https://github.com/kit-parco/networkit/blob/5cc74b434b4891ea53a278777a3699a26bedf379/networkit/_NetworKit.pyx#L6550) extend both `Algorithm` and `DynAlgorithm`. However, it seems that there is no easy way to do it in Cython.

**Comment by bernlu** [comment]
fixed in #1067
