### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by manpen** [networkit/networkit#223]
This issue is related to #38, but broader; hence I opened another issue.

Since the moving to cmake, some of the DevGuide is obsolete and needs to be changed; it seems however not to be included in the main repository. The version contained in the repository still mentions Mercurial rather than git. Also I think it's questionable that student exercises and project are contained in the repository.

**Comment by hmeyerhenke** [comment]
The README.md file is also outdated. It stil talks about ipython when it should be jupyter (and probably several other things). Alexander, can this be delegated to a student?

**Comment by hmeyerhenke** [comment]
The user guide loads the PGP graph -- well, it tries. It seems that the PGP graph was deleted from the repository when there was a major cleanup. Please fix this inconsistency, a working user guide is of utomost importance!

**Comment by avdgrinten** [comment]
I will look into this next week.
