### ISSUE TITLE
Reducing CI latency

### ISSUE THREAD

**Issue by avdgrinten** [networkit/networkit#236]
Our Travis configuration needs quite a lot of time to finish execution. I would like to reduce the latency of the build.

Current for every OS/compiler we do the following:

- Install the Python package (includes building with CMake).
- Run the Python tests.
- Re-build NetworKit core in debug mode.
- Run the C++ tests in debug mode.
- Re-build NetworKit core in release mode.
- Run the C++ tests in release mode.
- Re-build NetworKit core in non-monolithic release mode.
- Run the C++ tests in non-monolithic release mode.

IMHO this is a bit too much (a single execution of that script takes 45 min on Travis). What I propose to do instead is:

- Build the C++ library in release mode.
- Build the Python package (potentially re-using the C++ library built before).
- Run the C++ tests.
- Run the Python tests.

These changes would bring down the Travis latency to about 15 min (= the time required for a C++ build + running the tests). Such a script could be run for multiple OS/compiler combinations.

Assuming that those things work, more exotic configurations (e.g. non-monolithic builds, debug builds or C++14/17 builds) are likely to work, too. Thus, we do not need to test for them on many OS/compiler configurations - one or two additional configurations that check them should be sufficient. Increasing the number of configurations while reducing the work/configuration makes sense as it increases the amount of parallelism in the CI pipeline.

Any objections or comments? Pinging @manpen as he wrote the majority of the current configuration.

**Comment by manpen** [comment]
I agree in most parts, but I think it's important to build the library in both in Release and Debug mode, as the code is not identical (due to preprocessor directives) and we should make sure that either compiles.
Hence I suggest to build and test the C++ lib in debug mode (as it include more assertions).
Then we can build the Python library as release (as it's the default).
In my opinion we should keep both compilation runs separate (i.e. do not reuse stuff in PIP) to make sure that the PIP are doing okay.

**Comment by avdgrinten** [comment]
Good point about keep the debugging configurations. In PR #237 I kept them as separate configurations.

I still suggest to teach `setup.py` to use an existing `libnetworkit.so` so that we do not have to build the C++ library twice. `setup.py`/`pip` would still build the `_NetworKit.something.so` so that this part of the build system would still be tested. Doing this would almost halve the time required for most configurations.

**Comment by avdgrinten** [comment]
After #240, Travis takes about 20 minutes for a full build. 10 minutes are required to compile NetworKit (in release mode). About one minute could be avoided if TLX was not built twice (once for the core library and once for the Python extension).

However, the installation of pandas takes another 5-10 minutes. I will look into either caching the pandas installation on Travis or building NetworKit without pandas support to reduce the build time to a minimum.

**Comment by fabratu** [comment]
Closing this. Switched from travis to github actions, which reduced the test-time significantly.
