### ISSUE TITLE
Profiling module broken

### ISSUE THREAD

**Issue by angriman** [networkit/networkit#241]
@hmeyerhenke noticed that after recent PRs were merged the profiling module is broken. The error seems to be related to some plots that cannot be drawn as they receive NoneType objects or they encounter divisions by zero.

I never worked with the profiling module before so I find it quite difficult to debug it as there is almost no documentation.

**Comment by hmeyerhenke** [comment]
Maybe it's time for refactoring (and resulting documentation) then. How should it look like in your opinion?

**Comment by mjspeck** [comment]
I'm having the same issue. Anymore progress on this issue?

**Comment by angriman** [comment]
We recently fixed this issue by removing the feature causing the error, the profiling module should work now. Are you using the last version of NetworKit?

**Comment by mjspeck** [comment]
Looks like it. I'm on version 8.0

**Comment by mjspeck** [comment]
One thing I found: building from source fixes it. But Pypi version still seems to have the division by zero error.

**Comment by angriman** [comment]
That's probably due to a wrong parameter initialization in `KatzCentrality` that has been fixed in #648. Unfortunately, that fix came after the 8.0 release. With the next release profiling should work also with the Pypi version.

**Comment by mjspeck** [comment]
Ah, gotcha. Thanks for the quick responses.
