### ISSUE TITLE
UserGuide fails at graph.BFS(G, v)

### ISSUE THREAD

**Issue by PaulSorenson** [networkit/networkit#260]
I replaced 
`graph.BFS(G, v)`
with  
`distance.BFS(G, v)`
and it seems to work.

There seem to be additional references to `graph` that work when replaced with `distance`.

**Comment by eug93** [comment]
Hi, thank you for your message.

`distance.BFS(G, v)` is correct, some algorithms like `BFS` were initially implemented within the `graph` module but now they are in the `distance` module.
In some cases the NetworKit user guide is indeed outdated, we are working on that.

You can find more details in the [documentation](https://networkit.github.io/dev-docs/python_api/distance.html?highlight=bfs#networkit.distance.BFS).

**Comment by PaulSorenson** [comment]
No problem and I guessed that was the reason. Close it at your convenience - I have worked around it.

**Comment by angriman** [comment]
This issue has been addressed, I am closing it.
