### ISSUE TITLE
Update documentation on how to use NetworKit as a library

### ISSUE THREAD

**Issue by ion-turcanu** [networkit/networkit#323]
Could you please update the documentation regarding the usage of NetworKit as a library for other C++ projects?

**Comment by avdgrinten** [comment]
In principle, the instructions in our README should work.

In addition to that, we now also support `pkgconfig`. You can build the C++ core (as described in the README), install it using `make install` and use `pkgconfig` (search on Google for a description) to find the include directories and libraries.

**Comment by ion-turcanu** [comment]
Thank you Alexander. The section _Use NetworKit as a library_ says that one could include the library as following:
`#include <NetworKit/graph/Graph.h>`
First, there is no `Graph.h` file, now it is `Graph.hpp`. Second, the example says that the header should be in `-I/path/to/build/directory/include`, but in reality the headers directory is `networkit/include/networkit`. Third, the file `LibDemo.cpp` is missing.

In any case, I am not able to use NetworKit as a library in OMNeT++, but I guess I'll open a separate thread for this.
