### ISSUE TITLE
Reformat indentation globally

### ISSUE THREAD

**Issue by avdgrinten** [networkit/networkit#329]
@manpen mentioned in a comment (https://github.com/kit-parco/networkit/issues/173#issuecomment-499815102) that people sometimes reformat the code due to inconsistencies in coding style.

I would like to get the indentation fixed everywhere. I think we agreed on 4 space indentation at the NetworKit dev meeting last year, so changing to that style should be uncontroversial. We should apply such this change globally.

While it would be fine to provide a clang-format file with sane defaults (that could be used for new files or by new contributors), I do not want to reformat the code base globally. Hence, I would like to ban reformatting existing code for no good reason. If contributors use clang-format or any other tool locally, they should only apply those tools to the new chunks of code that they write but not globally to entire files (and, of course, the existing style in each file still needs to be respected).

**Comment by manpen** [comment]
Solved in PR #411
