### ISSUE TITLE
Consider submitting NetworKit to Spack

### ISSUE THREAD

**Issue by michitux** [networkit/networkit#338]
Last week I attended [PASC19](http://pasc19.pasc-conference.org/) and there I learned about [Spack](https://spack.io/), a package manager apparently popular in HPC. It easily allows to install multiple versions of packackages, also with custom compilers etc. They already [package networkx](https://github.com/spack/spack/blob/master/var/spack/repos/builtin/packages/py-networkx/package.py), so I guess it could be a good idea to also submit NetworKit to their package repository to make it easier to use.

**Comment by fabratu** [comment]
@michitux Thx for the suggestion. I will have a look into it.

**Comment by fabratu** [comment]
As an update: We are currently working on bringing NetworKit to different package managers with the next update. Spack is one (promising) consideration.

**Comment by fabratu** [comment]
Closing this issue. NetworKit is now available via spack:

- complete software: spack install py-networkit
- core library only: spack install libnetworkit
