### ISSUE TITLE
Error in algorithm DynBetweenness

### ISSUE THREAD

**Issue by gilcu3** [networkit/networkit#339]
Algorithm DynBetweenness returns wrong results. Minimal example:
Directed Graph with nodes {0, 1, 2} and edges {(0, 1), (1, 2)}. When edge (2, 0) is inserted, the aforementioned algorithm returns that the betweenness of node 0 is 0, and it should be 1.

**Comment by angriman** [comment]
Hi, dynamic algorithms do not update the ranking automatically, you should use the `update` method as reported [here](https://networkit.github.io/dev-docs/python_api/centrality.html?highlight=dynbetw#networkit.centrality.DynBetweenness.update). The `update` method gets a `GraphEvent` as input, for example:

```
g = Graph(3, False, True)
g.addEdge(0, 1)
g.addEdge(1, 2)

db = centrality.DynBetweenness(g)
db.run()
print(db.ranking()) # [(1, 1.0), (0, 0.0), (2, 0.0)]

g.addEdge(2,0) # Add new edge (2, 0)
# Update the ranking
db.update(dynamic.GraphEvent(dynamic.GraphEvent.EDGE_ADDITION, 2, 0, 1))
print(db.ranking()) # [(0, 1.0), (1, 1.0), (2, 1.0)]
```

To do multiple updates at once, use `updateBatch`, more about it [here](https://networkit.github.io/dev-docs/python_api/centrality.html?highlight=dynbetw#networkit.centrality.DynBetweenness.updateBatch).

**Comment by gilcu3** [comment]
Thank you for your response, I forgot to say, I am using the library from c++, and the master branch. This is my code:
```
auto d = DynBetweenness(g);
d.run();
auto e = GraphEvent(GraphEvent::EDGE_ADDITION, edge.first, edge.second);
d.update(e);
d.scores();
```

Which branch did you test?

**Comment by angriman** [comment]
I tested the Dev branch, but the implementation of `DynBetweenness` should be the same in both branches.

As you wrote, you should insert the edge (2, 0) to the graph (i.e., run `g.addEdge(2,0)`) before doing the update. By design, all NetworKit classes implementing algorithms (like `DynBetweenness`) are not allowed to make changes to the input graphs; otherwise, if you had another dynamic algorithm class working on the same graph `g`, they would have added the same edge twice.

A working example in C++ would be:

```
#include <networkit/centrality/DynBetweenness.hpp>
#include <networkit/dynamics/GraphEvent.hpp>
#include <networkit/graph/Graph.hpp>
#include <networkit/auxiliary/Log.hpp>

using namespace NetworKit;
int main(int argc, const char *argv[]) {
    Graph G(3, false, true);
    G.addEdge(0, 1);
    G.addEdge(1, 2);

    DynBetweenness dynB(G);
    dynB.run();
    INFO(dynB.ranking());

    G.addEdge(2, 0);
    GraphEvent ge(GraphEvent::EDGE_ADDITION, 2, 0);
    dynB.update(ge);
    INFO(dynB.ranking());
    return 0;
}

Output:
[INFO ]: [(1, 1), (0, 0), (2, 0)]
[INFO ]: Diameter: 2
[INFO ]: Entering update
[INFO ]: Old distance: 1.79769e+308
[INFO ]: Phase 1. distances[2][0] = 1.79769e+308, and G.weight2, 0 = 1
[INFO ]: Entering bfs
[INFO ]: [(0, 1), (1, 1), (2, 1)]
```

**Comment by angriman** [comment]
That's indeed a bug, thank you for finding this issue, we will fix that.

**Comment by gilcu3** [comment]
Well, as the issue is not yet closed, I want to pinpoint another (potential) error.
```
#include <networkit/centrality/DynBetweenness.hpp>
#include <networkit/dynamics/GraphEvent.hpp>
#include <networkit/graph/Graph.hpp>
#include <networkit/auxiliary/Log.hpp>

using namespace NetworKit;
int main(int argc, const char *argv[]) {
    Graph G(3, false, true);
    G.addEdge(2, 1);

    DynBetweenness dynB(G);
    dynB.run();
    INFO(dynB.ranking());

    G.addEdge(2, 0);
    GraphEvent ge(GraphEvent::EDGE_ADDITION, 2, 0);
    dynB.update(ge);
    INFO(dynB.ranking());
    return 0;
}
```
A slight modification in your example above, gives an undefined result:
```
[INFO ]: [(0, 0), (1, 0), (2, 0)]
[INFO ]: Diameter: 1
[INFO ]: Entering update
[INFO ]: Old distance: 1.79769e+308
[INFO ]: Phase 1. distances[2][0] = 1.79769e+308, and G.weight2, 0 = 1
[INFO ]: Entering bfs
[INFO ]: [(0, 0), (1, -nan), (2, 0)]
```

**Comment by angriman** [comment]
Thank you for solving this issue, it would be nice if you open a new PR so you can get the credit you deserve for this fix.

**Comment by gilcu3** [comment]
> Thank you for solving this issue, it would be nice if you open a new PR so you can get the credit you deserve for this fix.

Done #352
