### ISSUE TITLE
`Global.h` defines PI in global namespace

### ISSUE THREAD

**Issue by manpen** [networkit/networkit#363]
In [`include/networkit/Globals.hpp`](https://github.com/networkit/networkit/blob/21950fa590da3e5fb93a787019e3119c12ba017b/include/networkit/Globals.hpp#L38) we defined `PI` which reaches into global namespace. I consider this a bug and would like to move PI into the `NetworKit` namespace. Can we do this, or should there be a previous deprecation warning?

Also I do not understand why  `2.0*std::acos(0)` is so much better than writing down the constant (as in Intel's case) that we need a case distinction. Wouldn't it be better to just have the constant?

**Comment by avdgrinten** [comment]
Yes, this is indeed bad practice. Writing down the digits is preferable to allow constexpr initialization. But make sure that you have enough digits for double precision.

**Comment by manpen** [comment]
Issue #367 deals with this and the discussion take place there. So I'm closing this issue.
