### ISSUE TITLE
Better distribution for NetworKit C++ headers

### ISSUE THREAD

**Issue by angriman** [networkit/networkit#382]
At the moment, to install the NetworKit C++ headers one has to manually clone the repository, compile it and install (or use conda). However, for most external users it would be nicer to have a single command to do so. I think that Homebrew is a good candidate for this purpose, as it is compatible with both Linux and MacOS. However, I also understand that it might not be very popular among Linux users. What do you think?

If we agree on distributing NetworKit via homebrew (or another popular package manager), we might want to schedule a new NetworKit release, as [NetworKit 5.0](https://github.com/networkit/networkit/releases) cannot be compiled on mac os with Apple Clang.

**Comment by manpen** [comment]
As you already mentioned `homebrew` seems to not be used on Linux that much (as these systems typically ship a proper ~~AppStore~~ package manager); so I do not have an opinion about the `homebrew` aspect. Remarks about the release:
- Yes, we should have a new one, since a lot has happened.
- As there are plans to meet, I suggest to schedule the release after that. The simple reason is that we want to have one stable release between deprecation and removal of features. IMHO we should wait, just in case we want to deprecate.
- I would ask for an announcement a couple of weeks ahead, so everybody has to chance to get PRs in (I have some, which are not urgent but which I would like to see in the next release).
- Should we use the chance and move to C++14 after the release? (it's five years now ... so compiler should be available)

**Comment by hmeyerhenke** [comment]
Regarding C++ 14: This decision should not be taken easily. Compilers are typically available on one's own machine. But that's not necessarily true for compute servers / computing center clusters. I'm not saying we should not do it -- my point is that we should be careful in this respect (e.g. ask the mailing list if someone needs a compiler older than these versions of GCC or whatever else might be used.

**Comment by avdgrinten** [comment]
In my opinion, we should define some policy about which compilers we support. The set of C++ features that we allow would then be defined by those compilers. For example, such a policy could demand that 1) we support the default compiler on Linux distributions X, Y and Z, or, 2) we support all major GCC / Clang releases not older than X years.

**Comment by manpen** [comment]
I agree -- we also used to have this problem in our CSC. But usually it's quite easy to use [spack](https://github.com/spack/spack) (see also #338) or to manually build the compiler. As a side note: We're requiring Python 3.4 which was release late 2014. So it's comparably "old".

**Comment by manpen** [comment]
Just for reference a small list of compilers vs distros. 

GCC [fully supported](https://gcc.gnu.org/projects/cxx-status.html#cxx14) C++14 with version 5.1 (released Apr. 2015 [source](https://www.gnu.org/software/gcc/releases.html) ); Clang [full supported](https://clang.llvm.org/cxx_status.html) with version 3.4 (released Jan 2014 [source](http://releases.llvm.org/) ). 

Ubuntu 16.04 (LTS) includes gcc 5.3
SLES 11 (still in LTS support) supports gcc 5.2  
CentOS/RHEL7 only supports gcc 4.8 [source](https://access.redhat.com/solutions/19458)

So if we link it to an LTS distro running in CSCs (RHEL/CentOS/Scientific Linux), we're fixed to C++11 for roughly the next four years.

**Comment by avdgrinten** [comment]
I was about to post the same. On second thoughts, it is probably not a good idea to tie our support to a list of distributions as this would mean that in 4 years, we will jump from GCC 4.8 to GCC 8 (!). Hence, my proposal would be to support major GCC and Clang versions for 5 years. For GCC, this matches our current support level (on the CI servers) right now, and it gives us the chance to use GCC 5.1 features in 8 months. For Clang, we would be bound to Clang 3.8 for two more years - but Clang 3.8 already fully supports C++14 and some features of C++17.

The exact support period would be negotiable. I would be fine with anything <= 5 years but >= 3, with a tendency to longer support. Even Google's [Abseil](https://abseil.io/docs/cpp/platforms/platforms) library which explicitly does not intend to support legacy platforms, still supports GCC 4.8. Boost still supports GCC 4.7.

**Comment by hmeyerhenke** [comment]
@avdgrinten: I think 5 years makes sense. Why don't you put this proposal on the mailing list and ask for comments? Include Manuel's research on the versions. What about the Intel compiler?

**Comment by fabratu** [comment]
The headers can now be installed seperately via conda, spack and homebrew. The package is called `libnetworkit`everywhere.

**Comment by angriman** [comment]
Thank you, I am closing this.
