### ISSUE TITLE
Complexity of BiconnectedComponents

### ISSUE THREAD

**Issue by gilcu3** [networkit/networkit#398]
As far I can see, your implementation of Tarjan's algorithm for finding biconnected components is not linear as expected. The culprit is line https://github.com/networkit/networkit/blob/cd5c91511a0fe045011ef8a27d56220641203554/networkit/cpp/components/BiconnectedComponents.cpp#L63, in which neighbours will be visited several times, as the neighbours visited already must be remember somehow to avoid redundant computations. A test case for which this behavior is present is not hard to construct.

**Comment by avdgrinten** [comment]
This is indeed problematic, thank you for the report. As a fix, we could store the neighbor iterator on the stack, in addition to the node that we are expanding.

**Comment by gilcu3** [comment]
> This is indeed problematic, thank you for the report. As a fix, we could store the neighbor iterator on the stack, in addition to the node that we are expanding.

Yes exactly the standard solution :)

**Comment by angriman** [comment]
Thank you @gilcu3 for reporting this issue. I've addressed it in #405.
