### ISSUE TITLE
Add CPP-like overloads for Graph.for* callbacks

### ISSUE THREAD

**Issue by manpen** [networkit/networkit#401]
It would be nice to have similar semantics for the CPP and Python interfaces (i.e. overloads for different signatures). While we cannot distinguish between overloads for `edgeweight` and `edgeindex`, we could easily support the following signatures: (u), (u,v), (u,v,w,eid). A solution could be as follows:

```Python
import inspect

[...]

cdef cppclass EdgeCallBackWrapper:
	void* callback
	object fu

	__init__(object callback):
		n = len(inspect.signature(callback).parameters.items())
		if n == 1:
				this.fu = lambda u, v, w, eid: callback(v)
		elif n == 2:
				this.fu = lambda u, v, w, eid: callback(u, v)
		elif n == 4:
				this.fu = callback
		else:
    				throw_runtime_error(stdstring("Unsupported signature"))

		this.callback = <void*>this.fu
[...]
```

_Originally posted by @manpen in https://github.com/networkit/networkit/pull/400#issuecomment-522914106_

**Comment by manpen** [comment]
@angriman add in #400:
I agree with overloading different signatures, this would simply a lot the usage of that function.
Also, it might be better to write some Python iterators to iterate over nodes/neighbors more easily and efficiently.

**Comment by avdgrinten** [comment]
I am a bit concerned about the robustness of this solution. It does work for functions with only positional parameters, but how does it behave with keyword arguments, or `*args`? What if the callback is not a function but an object with `__call__`? In general, such overloading seems to be quite unexpected in Python.

An orthogonal feature that I would like to see implemented is exporting `neighborRange` to Python by wrapping it in a Python iterator -- that would allow much more natural iteration in Python than `forNeighbors()`. I would also expect it to be faster: `forNeighbors()` has to type-erase the Python callback when passing it to C++; in principle, `neighborRange` can do much better here (but I don'T know the implementation details in CPython).

**Comment by manpen** [comment]
Based on @avdgrinten comments and PR #406, I'm closing this issue.
