### ISSUE TITLE
AttributeError: 'networkit._NetworKit.SNAPGraphReader' object has no attribute 'isDirected'

### ISSUE THREAD

**Issue by JunpengCode** [networkit/networkit#417]
import networkit as nk
import networkx as nx
import sys

if __name__ == '__main__':
    G = nk.graphio.SNAPGraphReader("./facebook_combined.txt")
    nxG = nk.nxadapter.nk2nx(G)   # error

**Comment by JunpengCode** [comment]
And the code line `nk.readGraph("./facebook_combind.txt", nk.Format.SNAP)` is error.  Why?

**Comment by JunpengCode** [comment]
file format:

0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20

**Comment by JunpengCode** [comment]
import networkit as nk
import networkx as nx



if __name__ == '__main__':
    G = nk.graphio.SNAPGraphReader("./facebook_combined.txt")
    # nxG = nk.nxadapter.nk2nx(G)   # error
    nxG = nx.Graph()
    nxG.add_edges_from(G.edges())


Error message is : AttributeError: 'networkit._NetworKit.SNAPGraphReader' object has no attribute 'edges'

**Comment by angriman** [comment]
> import networkit as nk
> import networkx as nx
> import sys
> 
> if **name** == '**main**':
> G = nk.graphio.SNAPGraphReader("./facebook_combined.txt")
> nxG = nk.nxadapter.nk2nx(G) # error

Here `G` is not a graph object, but a `SNAPGraphReader`. To read the graph you need to use the `read` method like this:
```
G = nk.graphio.SNAPGraphReader().read("./facebook_combined.txt")
```

> And the code line `nk.readGraph("./facebook_combind.txt", nk.Format.SNAP)` is error. Why?

I guess that you just misspelled the input graph name (use `facebook_combined.txt` instead of `facebook_combind.txt`).

**Comment by JunpengCode** [comment]
import networkit as nk
import networkx as nx

if __name__ == '__main__':
    G = nk.readGraph("./facebook_combined.txt", nk.Format.SNAP)
    nxG = nk.nxadapter.nk2nx(G)   
    print(nxG.number_of_nodes())


error message is : Segmentation fault (core dumped)
