### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JunpengCode** [networkit/networkit#418]
import networkit as nk
import networkx as nx

if name == 'main':
G = nk.readGraph("./facebook_combined.txt", nk.Format.SNAP)
nxG = nk.nxadapter.nk2nx(G)
print(nxG.number_of_nodes())

error message is : Segmentation fault (core dumped)

**Comment by angriman** [comment]
Did you install NetworKit from pip? If so, this might be an issue affecting the last release of NetworKit. You can solve it by pulling from the `Dev` branch of NetworKit, and installing it with
```
pip3 install --user -e .
```

Otherwise, I suggest you to use the NetworKit `SNAPGraphReader`:
```
import networkit as nk
import networkx as nx

G = nk.graphio.SNAPGraphReader().read("./facebook_combined.txt")
nxG = nk.nxadapter.nk2nx(G)
print(nxG.number_of_nodes())
```

**Comment by JunpengCode** [comment]
solved! Thanks angriman!  I reinstall the networkit using `pip install --user -e .`.
