### ISSUE TITLE
Triangle Counting

### ISSUE THREAD

**Issue by csverma610** [networkit/networkit#422]
Hello,

Can someone explain how to count triangles from the EdgeScore? 

Thanks

**Comment by hmeyerhenke** [comment]
Please take a look at LocalClusteringCoefficient.cpp in module/folder centrality. The run() method counts triangles (but also does other stuff).

**Comment by angriman** [comment]
AFAICS there is no way to retrieve the number of triangles from Python. Some triangle counting algorithms are implemented in the C++ core (e.g., `LocalClusteringCoefficient` seems to do so). I think writing a Python wrapper for at least one them makes sense.
@michitux do you have any suggestions about which algorithm we should use for this purpose?

**Comment by michitux** [comment]
`LocalClusteringCoefficient` in the turbo mode and `TriangleEdgeScore` both implement the same algorithm, which is the algorithm I would recommend. It would make sense though to refactor this code and extract the common triangle counting parts, in particular if there shall be a third place to count triangles now. There is also `ChibaNishizekiTriangleEdgeScore` which should rather be deprecated I think.

@csverma610 On what level do you want to count triangles? Globally? If globally is your goal, just get the `scores()` from `TriangleEdgeScore`, build a sum over the counts you get and divide them by 3, as every triangle is counted at each of its three edges. Note that you need to call `indexEdges()` on the graph before computing any edge score. The following code gives you the number of triangles of the graph:

```python
import networkit as nk
nk.readGraph("input/karate.graph", nk.Format.METIS)
G.indexEdges()
nk.sparsification.TriangleEdgeScore(G).run()
print(sum(triangles.scores())/3)
```

In this example, the output should be `45.0`.

**Comment by csverma610** [comment]
Hello Michael,

Thank you very much. I do not understand why sparsification is need? In
addition, what indexEdges will do, isn't it is given by the reader or part
of software internal?

Regards

**Comment by michitux** [comment]
There is no sparsification needed, the triangle counting algorithm is only exported to Python as part of the sparsification module as it is used there. By default, networkit graphs do not have ids for edges, but all algorithms that store a score for every edge need it. Calling `indexEdges()` generates these edge ids. 

Triangular meshes might have more triangles than there are triangular faces in the mesh as triangles might be subdivided. The triangle counting in NetworKit should be exact. Can you provide an example where the count is not exact?

**Comment by csverma610** [comment]
Hello,

I am trying to find a simple example which I can debug to ascertain the
correctness of algorithm. However, I downloaded
a data from:

http://networkrepository.com/brock200_1.php

For this example, the link says there are 1.6M triangles but NetworKit
gives 543700.

csv

**Comment by hmeyerhenke** [comment]
Sounds a bit like the normalization with the factor 3 is missing... Is the fraction between the two values exactly 3?

**Comment by angriman** [comment]
This issue has been resolved, I am closing it.
