### ISSUE TITLE
Installation problem on windows using anaconda

### ISSUE THREAD

**Issue by Chuan1997** [networkit/networkit#442]
So my question is, the current version of NetworKit cannot support anaconda?
![image](https://user-images.githubusercontent.com/34181999/67735357-d467ce80-fa3e-11e9-8c16-344142034b54.png)
I can find packages available for anaconda, but still cannot install.
![image](https://user-images.githubusercontent.com/34181999/67735463-2d376700-fa3f-11e9-9564-7e633ab7bb30.png)

**Comment by avdgrinten** [comment]
NetworKit can be installed through anaconda. However, the current version does not work natively in Windows. You should be able to use NetworKit via WSL (the Window Subsystem for Linux).

**Comment by Chuan1997** [comment]
But my system is Windows 7, the WSL cannot be set up?

**Comment by hmeyerhenke** [comment]
Even Microsoft does not support Win 7 any more. As far as I know, WSL is not available for it (and thus never will be). It is time to upgrade.

**Comment by fabratu** [comment]
WSL is integrated in certain Windows-Kernels, which are only generally available in Windows 10 1607 (aka Anniversary Update) and newer. This means even back-porting is no option. If you want to stay with Windows 7, unfortunately a VM is the way to go.
