### ISSUE TITLE
CommuteTimeDistance returns different commute times on same node pair.

### ISSUE THREAD

**Issue by cndolo** [networkit/networkit#447]
The CommuteTimeDistance class has, among others, a `run()` method and a `runSinglePair(u, v)` method to compute the commute time of given node pairs. `run` preprocesses the graph and computes the commute time for all node pairs; the commute time between a node pair u,v is then queried using `distance(u,v)`. `runSinglePair(u,v)` computes the the commute time between  u and v without preprocessing, and returns the commute time. 

The `distance(u,v)` and `runSinglePair(u,v)` should return the same commute time for the same node pairs, but do not. The returned values of both functions differ.

Here is my Python code to replicate this behaviour.

```
import networkit as nk
G = nk.Graph(6, False, False)
G.addEdge(0,2)
G.addEdge(1,2)
G.addEdge(2,3)
G.addEdge(2,4)
G.addEdge(3,5)
G.addEdge(4,5)
ctd = nk.distance.CommuteTimeDistance(G)
```
Using the `runSinglePair` method:
```
print(ctd.runSinglePair(0, 2))
2.449489742783178
 ```
Using the `distance()` method after preprocessing:

```
ctd.run()
print(ctd.distance(0, 2))
3.4641016151377544
```

**Comment by hmeyerhenke** [comment]
This deviation is indeed quite high and not tolerable. Could you please investigate what's going on there? In particular, is one method based on sampling and the other not (full computation)?

**Comment by hmeyerhenke** [comment]
Any progress on this issue?
