### ISSUE TITLE
Coding style: const in declarations and definitions

### ISSUE THREAD

**Issue by avdgrinten** [networkit/networkit#464]
Perhaps surprisingly (or not?), `const` on value types in declarations does not restrict the implementation: [compiler explorer](https://godbolt.org/z/jZ67Vt). This makes sense: after all, these arguments become local variables in the implementation and `const` on those local variables is an implementation detail. Since these `const` keywords do clutter the interface (and make the documentation and header files more verbose) without giving the user any useful information, I asked @cndolo to remove `const` from values types in declarations.

My suggestion is too keep it in the implementations (i.e., the function definitions in source files) for now. This has the advantage that the local variables remain constant. However, it results in a mismatch between header files and source files. Thoughts?

**Comment by angriman** [comment]
This is now checked by clang tidy (`readability-avoid-const-params-in-decls`).
