### ISSUE TITLE
Inclusion of layout algorithms?

### ISSUE THREAD

**Issue by ulupo** [networkit/networkit#467]
Congratulations on the awesome work done in this project!

I recently noticed that a [base class](https://github.com/networkit/networkit/blob/Dev/include/networkit/layout/LayoutAlgorithm.hpp) for layout algorithms has been added.  I was wondering: is there a roadmap for the implementation of a few popular layout algorithms without the need to resort to networkx?  It would be great to have these in interactive applications in which a graph is constructed depending on parameters, and needs to be re-computed as well as layed out every time a parameter is changed.

**Comment by hmeyerhenke** [comment]
At some point, we had some (very draft-y) implementations of some basic layout algorithms and other layout functionality (plus a good implementation of maxent-stress drawing). But most of them were removed to remain focused on network analysis algorithms. After all, the core development team is rather small.

Our recommendation regarding graph drawing and visualization is to attach to gephi. There should be a Jupyter notebook in the NetworKit repository that explains how to do that.

If somebody outside the current core development team would like to implement and maintain graph drawing functionality, we may reconsider this decision.

**Comment by ulupo** [comment]
Thanks for the comprehensive reply, @hmeyerhenke. I couldn't find that notebook but I do see that you have functionality for exporting to Gephi: https://github.com/networkit/networkit/search?p=1&q=gephi&unscoped_q=gephi.

**Comment by hmeyerhenke** [comment]
This notebook may have gotten lost when some major restructuring of the repository was done. Please find it attached.
[gephi-viz.ipynb.zip](https://github.com/networkit/networkit/files/4005315/gephi-viz.ipynb.zip)
