### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by isaiahshiner** [networkit/networkit#474]
Environment:

    isaiah@vps146036:~/test$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.6 LTS
    Release:        16.04
    Codename:       xenial
    isaiah@vps146036:~/test$ python --version
    Python 3.8.1
    isaiah@vps146036:~/test$ pip --version
    pip 19.3.1 from /home/isaiah/.local/lib/python3.8/site-packages/pip (python 3.8)
    isaiah@vps146036:~/test$ cmake --version
    cmake version 3.15.3
    isaiah@vps146036:~/test$ pip list | grep scipy
    scipy                    1.4.1                 
    isaiah@vps146036:~/test$ pip list | grep numpy
    numpy                    1.18.1
    isaiah@vps146036:~/test$ g++ --version
    g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

I tried `pip install --user networkit` and it failed. After sitting with `Building wheel for networkit (setup.py) ... -` for about 10 minutes, it spat out a very long list of errors. The full error log is [on pastebin.](https://pastebin.com/aCx49mTp)

Looking through the log, it seems very unhappy about a lot of methods being deprecated, but I don't know if they're fatal errors. This section, starting at line 610, seems important:

    [ 99%] Building CXX object CMakeFiles/networkit.dir/networkit/cpp/viz/PostscriptWriter.cpp.o
    [100%] Linking CXX shared library libnetworkit.so
    [100%] Built target networkit
    Scanning dependencies of target _NetworKit
    [100%] Building CXX object CMakeFiles/_NetworKit.dir/networkit/_NetworKit.cpp.o
    /tmp/pip-install-jsgf9qfw/networkit/networkit/_NetworKit.cpp:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    CMakeFiles/_NetworKit.dir/build.make:62: recipe for target  'CMakeFiles/_NetworKit.dir/networkit/_NetworKit.cpp.o' failed

I looked through the installation instructions again, and it doesn't look like I've done anything explicitly wrong. This could be an issue with my own Python installation, and has nothing to do with networkit.

Ah, on [this page](https://networkit.github.io/get_started.html) of your documentation, you said this: On macOS, it can happen that the g++ compiler is unable to locate specific Linux-based header files. An example would be an error during the compilation of a C++ header which includes stdint. This can generate the following error message: `fatal error: sys/_types/_int8_t.h: No such file or directory`. This error will most likely happen on new systems or after a major system upgrade. In this case you need to (again) install the Xcode command line tools: xcode-select --install. Afterwards the code should compile completely.

I'm not on macOS, but the missing header file looks similar.

Any ideas? Some help with this would be really awesome.

**Comment by isaiahshiner** [comment]
It was my fault, I just solved it myself. For anyone else solving this see this [SO issue](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory).

If you are on Python 3.8, do `sudo apt-get install python3.8-dev` and try installing networkit again.

I'm not sure whether I should close this myself. I also have a question.

Installation really did take 10 minutes. I assumed that was related to the bug. Is that normal? If I use this in a package, will all my downstream users have to wait for that long installation as well? In that case, maybe this isn't the right project for me. I'm not really doing data science anyway, just working with very large graphs.

**Comment by isaiahshiner** [comment]
I switched to NetworkX. Closing the issue.

**Comment by angriman** [comment]
Hi, NetworKit is mainly written in C++ and the code is compiled on the machine that you use to download it. Therefore, the compilation is expected to take some minutes (depending on the machine).
This process could be sped up by providing pre-compiled binary packages, but this option is not yet available.

Anyway, consider that compilation is a one-time operation, and parallel C++ code is generally much faster than a pure Python implementation, especially if you are dealing with very large graphs.

**Comment by isaiahshiner** [comment]
Ah, gotta compile the C++ at some point, that makes much more sense.

And I suppose the truth is that I don't know how large the graphs will be, or how expensive it will be to process them, compared to the other parts of the problem. I'm not really doing data science, and the graph is used mainly like a data structure. I'm just building the graph, and then traversing it while pulling data from the vertices. Does that sound like something that would normally be expensive? 

The other thing is that I'm deploying this project to normal everyday users, hopefully lots of users, to use in production code. For that reason, installation not taking 10 minutes is at least somewhat important. Maybe that's also unusual for these sorts of data science projects.

Well in any case, thanks for the help!
