### ISSUE TITLE
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

### ISSUE THREAD

**Issue by gijzelaerr** [networkit/networkit#489]
hi!

When using networkit I get this warning printed in my console:

`OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.`

using homebrew python 3.7 on OSX 10.15.

**Comment by angriman** [comment]
Thank you, that's because NetworKit is still using some deprecated openmp APIs so, we'll address this issue.

**Comment by angriman** [comment]
The patch has been merged. I am closing this issue, thank you again @gijzelaerr  for spotting this, and @cndolo for the patch.

**Comment by gijzelaerr** [comment]
no thank you! :)
