### ISSUE TITLE
High node IDs crash networkit

### ISSUE THREAD

**Issue by gijzelaerr** [networkit/networkit#490]
hi!

This code:
```
import networkit as nk
graph = nk.graph.Graph(directed=True)
for u, v in zip(range(10**8, 10**8+1000), range(10**9, 10**9+1000)):
    print(f"u: {u} v: {v}")
    graph.addEdge(u=u, v=v, addMissing=True)
```

will crash both 6.0 and dev networkit:

```
λ  python bla.py
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
u: 100000000 v: 1000000000
u: 100000001 v: 1000000001
[1]    94761 killed     python bla.py
```

tried with dev and 6.0 on python 3.7 on OSX 10.15. I discovered this since I was importing a database from neo4j and using the existing ID's as nodes. Lower numbers seem to work fine.

**Comment by angriman** [comment]
You are probably running out of memory, setting `addMissing=True` adds to the graph all nodes from 0 to the highest between `u` and `v` (which means that adjacency lists will be resized to max(u, v)). If you are running this on a laptop, it is not surprising that it crashes.

**Comment by gijzelaerr** [comment]
ah! Thanks for the quick response. My bad, I've been misunderstanding how I should use this. I didn't find in the docs how to add metadata or labels to a node, is it true that this is just not possible? With networkx this is possible, and it seems to be possible to convert between networkx and networkit. Thank you for your time and making a great library!

**Comment by angriman** [comment]
That's true, NetworKit is a more performance-oriented library so it does not allow to store internally additional labels or metadata. In the most simple cases this can be done externally e.g. creating a map from node/edge ids to their corresponding metadata/labels.

**Comment by avdgrinten** [comment]
To expand slightly: NetworKit does not have a built-in mechanism to store meta data, but you can of course easily store a dictionary (e.g., a Python `dict()`) or an array that maps node IDs to labels. NetworKit's node IDs are just integers, so this is usually quite simple.

**Comment by gijzelaerr** [comment]
ok perfect, thanks for the answer!

**Comment by rjurney** [comment]
@gijzelaerr unrelated to the ticket's topic - but do you have example code for creating a `networkit` network from a Neo4j database?
