### ISSUE TITLE
Python API to MaxEnt and PivotMDS only support 2D?

### ISSUE THREAD

**Issue by deklanw** [networkit/networkit#497]
In the Python API PivotMDS and MaxEnt both take a dim parameter

https://github.com/networkit/networkit/blob/345f2b8035176a0830d27f35e89c743d3b54d2ba/networkit/_NetworKit.pyx#L12346

https://github.com/networkit/networkit/blob/345f2b8035176a0830d27f35e89c743d3b54d2ba/networkit/_NetworKit.pyx#L12241

but, a pair is assumed in the constructor `vector[pair[double, double]]`

And, then here in `getCoordinates` a pair is assumed:
https://github.com/networkit/networkit/blob/345f2b8035176a0830d27f35e89c743d3b54d2ba/networkit/_NetworKit.pyx#L12147

And, anyway, I noticed that `writeGraphToGML` works in 3D, but if I instead wanted to include the point coordinates in the node data then save as GraphML, how would I do that?

Thanks.

**Comment by fabratu** [comment]
Closing this, since it was implemented in #877.
