### ISSUE TITLE
WattsStrogatz generation infinite loops if the ring lattice generated is complete

### ISSUE THREAD

**Issue by finnbar** [networkit/networkit#505]
Calling `WattsStrogatzGenerator(5,2,p)` for nonzero `p` will cause an infinite loop. This happens because `RegularRingLatticeGenerator(5,2)` generates a complete ring lattice, and thus the rewiring process of the Watts-Strogatz generator (https://github.com/networkit/networkit/blob/Dev/networkit/cpp/generators/WattsStrogatzGenerator.cpp#L42) never finds a suitable node to rewire to.

This happens for other complete lattices, such as `WattsStrogatzGenerator(7,3,p)`. Confusingly, these are cases that RegularRingLatticeGenerator should check for (https://github.com/networkit/networkit/blob/Dev/networkit/cpp/generators/RegularRingLatticeGenerator.cpp#L12) but this does not seem to be being checked in practice.

**Comment by angriman** [comment]
Thank you for bringing this to our attention. That's a bug indeed, we are working to solve it.

**Comment by cndolo** [comment]
The parameter `nNeighbors` in the `WattsStrogatzGenerator` specifies the  number of neighbours per node on each side, and not the total number of neighbours. 
The code runs in to an infinite loop during the rewiring process if the number of neighbours `k` is equal to the total number of nodes - 1, i.e. `k = n-1`.

Thanks for bringing this up; I will post a fix shortly.

**Comment by angriman** [comment]
The patch has been merged, I am closing this. Thanks again @finnbar for bringing this up.
