### ISSUE TITLE
Graph became multigraph when converting from Directed to Undirected

### ISSUE THREAD

**Issue by saibalmars** [networkit/networkit#518]
Hi, when I try to convert a directed graph to undirect graph, it seems that edge (1,2) is not going to be combined with edge (2,1). And the graph seems to become a graph with two edge (2,1). Is this the expected behavior? If yes, is there any parameter we can use to convert it into a graph with no duplicated edges? Thanks. 

(This is run on networkit 6.1)
``` python
import networkit as nk
G = nk.graph.Graph(3, directed=True)
G.addEdge(1,2)
G.addEdge(2,1)
G.edges()
Out[47]: [(1, 2), (2, 1)]

Gu = G.toUndirected()
Gu.edges()
Out[49]: [(2, 1), (2, 1)]

Gu.isDirected()
Out[50]: False

Gu.inNeighbors(1)
Out[51]: [2, 2]

```

**Comment by avdgrinten** [comment]
That is indeed somewhat unintuitive. You can use `removeMultiEdges()` to turn the multigraph into a graph again.

**Comment by angriman** [comment]
@saibalmars is this issue resolved?

**Comment by saibalmars** [comment]
@angriman Yeah that method works, just a little bit ugly :p
