### ISSUE TITLE
Missing dependency: ipython?

### ISSUE THREAD

**Issue by rschwarz** [networkit/networkit#519]
Hi, I installed networkit via `pip installed networkit` into an virtual environment using Python 3.7.3.
During the installation, only `numpy` and `scipy` were required:
```
[...]  Downloading networkit-6.1.tar.gz (2.0 MB)
 Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from networkit) (1.1.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from networkit) (1.16.2)
Building wheels for collected packages: networkit
[...]
Successfully installed networkit-6.1
```

But then, when I wanted to use it for the first time, I get:
```
$ python
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rs/src/litic/litic/serverside/scripts/test_func/venv3/lib/python3.7/site-packages/networkit/__init__.py", line 83, in <module>
    from .profiling import profiling
  File "/home/rs/src/litic/litic/serverside/scripts/test_func/venv3/lib/python3.7/site-packages/networkit/profiling/profiling.py", line 17, in <module>
    from IPython.core.display import *
ModuleNotFoundError: No module named 'IPython'
```

I think this might be a result of commit 142f29f402, were an attempt was made to reduce the number of dependencies.

So, I guess either `ipython` should be added back to [version.py](https://github.com/networkit/networkit/blob/Dev/version.py#L55), or it needs some conditional import?

**Comment by rschwarz** [comment]
Installing `ipython` fixed this problem, that is, there are no further missing dependencies.

**Comment by avdgrinten** [comment]
That looks like a bug indeed. Thanks for the report. @cndolo, could you add the required conditionals?

**Comment by cndolo** [comment]
I have opened PR #520 addressing this bug.

**Comment by cndolo** [comment]
Closing this as it has since been resolved. Thank you for reporting @rschwarz .
