### ISSUE TITLE
Make SSSP:getPredecessor return a const lvalue reference?

### ISSUE THREAD

**Issue by rionda** [networkit/networkit#533]
https://github.com/networkit/networkit/blob/ecb1af8c2c6ef3c484b45cdb9fdead584cbd94bc/include/networkit/distance/SSSP.hpp#L204

It seems excessive to have any caller pay for a copy (if I'm not mistaken), when they may just need a const lvalue reference. Could we change the signature of this method?

**Comment by YanzheL** [comment]
Good point, I suggest use

```c++
inline const std::vector<node>& SSSP::getPredecessors(node t) const { 
```

From my observation of APSP, as for an undirected weighted graph with 3 million nodes and 14 million edges, the memory size of distance matrix of `APSP` is nearly 14GB+. Due to the copy overhead of
```c++
std::vector<std::vector<edgeweight>> APSP::getPredecessors() const {
```
the memory usage will be doubled, which is unacceptable.

**Comment by hmeyerhenke** [comment]
Sounds reasonable. @avdgrinten , @fabratu -- following the usual procedure, is it possible to integrate the change into the upcoming release?

**Comment by fabratu** [comment]
From a schedule perspective, yes. We need to have an approved PR 7 days before merging it in (exception can happen though) . Will take a closer look at the matter at hand.

**Comment by rionda** [comment]
Closing as the relevant change has been merged. Thanks!
