### ISSUE TITLE
Memory leak when updating graphs

### ISSUE THREAD

**Issue by NicolasGensollen** [networkit/networkit#537]
Hello,

I'm running on what could be a memory leak issue when updating a graph a very large number of times. 

More precisely, I have a stream of interactions encoded as a basic text file (`stream.txt` in the code below). Each line is a `t u v` triplet meaning that `u` interacts with `v` at time `t`, and there are usually hundreds of billions of lines.  In addition, `u` and `v` are integers and are sorted. 
For example, the first 5 lines look like this:

```
1389296938.0 0 1
1389297042.0 2 3
1389297136.5 4 5
1389296898.5 6 7
1389297020.5 8 9
```
My goal is to parse this file line by line and maintain a simple graph that contains the `k` last interactions. Below is a simplified Python script that does that in addition to monitoring the memory consumption:

```python
def getCurrentMemoryUsage():
    ''' Memory usage in MB '''
    with open('/proc/self/status') as f:
        memusage = f.read().split('VmRSS:')[1].split('\n')[0][:-3]
    return int(memusage.strip()) * 10**-3

start = time.time()
stream_filename = "./stream.txt"
number_of_interactions = 153 * 10**6
number_of_nodes = 10**6
current_interaction = 0
window = 10
queue = []
counter = dict()
interaction_timers = 0
memory_usage = [0 for _ in range(int(number_of_interactions/10**6))]

H = nk.Graph()
# Add and remove nodes to "pre-allocate node memory"
for n in range(number_of_nodes):
	H.addNode()
	H.removeNode(n)	

assert H.upperNodeIdBound() == number_of_nodes

with open(stream_filename, "r") as fp:
	for line in fp:
		current_interaction += 1
		if current_interaction % 10**6 == 0:
			print(f"--> Interaction {current_interaction}...")
			print(f"Memory usage = {getCurrentMemoryUsage()}")
			memory_usage[int(current_interaction/10**6)-1] = getCurrentMemoryUsage()
		start_in = time.time()
		interaction = line.strip().split(" ")
		t,u,v = interaction[:3]
		t = float(t)
		u_idx = int(u)
		v_idx = int(v)
		if not H.hasNode(u_idx):
			H.restoreNode(u_idx)
		if not H.hasNode(v_idx):
			H.restoreNode(v_idx)
		if not H.hasEdge(u_idx,v_idx):
			H.addEdge(u_idx,v_idx)
		if u_idx <= v_idx:
			queue.append((t,u_idx,v_idx))
			if (u_idx,v_idx) in counter:
				counter[(u_idx,v_idx)] += 1
			else:
				counter[(u_idx,v_idx)] = 1
		else:
			queue.append((t,v_idx,u_idx))
			if (v_idx,u_idx) in counter:
				counter[(v_idx,u_idx)] += 1
			else:
				counter[(v_idx,u_idx)] = 1
		while len(queue) > window:
			temp = queue.pop(0)
			a,b = temp[1:]
			counter[(a,b)] -= 1
			if counter[(a,b)] == 0 and H.hasEdge(a,b):
				H.removeEdge(a,b)
				del counter[(a,b)]
				if H.degree(a) == 0:
					H.removeNode(a)
				if H.degree(b) == 0:
					H.removeNode(b)
	end_in = time.time()
	interaction_timers += end_in - start_in
end = time.time()
timer_value = end - start
print(f"Overall processing time = {timer_value}")
print(f"Average interaction processing time ={interaction_timers/number_of_interactions}")
fig = plt.figure()
plt.plot(memory_usage, linewidth=3)
plt.tight_layout()
plt.savefig("./memory_consumption_networkit.png")
```

I was expecting the memory consumption to be stable when running this since I'm not storing anything and the graph has a constant max size of `window` edges. Nonetheless, when running this script, the memory consumption increases continuously as shown in the following figure (X axis is the number of interactions in millions, and Y axis is the process memory consumption in MB):

![memory_consumption_networkit](https://user-images.githubusercontent.com/2639645/81275081-75b88880-9051-11ea-8049-35494f224c1c.png)

As a side note, I ran the exact same script with `NetworkX`, resulting in a much slower execution but the memory usage was constant.

Am I missing something here?

**Comment by michitux** [comment]
NetworKit dose not delete edges but just stores an invalid node marker. You can call `compactEdges()` on the graph to remove those invalid node markers. This won't actually free memory but should improve performance and if you add edges to the same nodes again this should not allocate additional memory. The graph has also a `shrinkToFit()` method that should free the memory, but this method has not been exposed to Python (but would be trivial to add to the Python interface).

**Comment by NicolasGensollen** [comment]
Thank you for your answer @michitux ! 
Indeed, I exposed `shrinkToFit()` to the Python interface and it seems to solve my problem.
