### ISSUE TITLE
nodes() is deprecated, but what now?

### ISSUE THREAD

**Issue by chroeseler** [networkit/networkit#563]
I'm almost embarrassed to ask, but I just started using networkit. Coming from Networkx is immediately used graph.nodes(). 
Now I see that nodes() is deprecated but I don't understand how else could get a list of my nodes? 
What am I missing? 
Thanks in advance for this, probably obvious, answer. 

Vg

**Comment by angriman** [comment]
Hi, `graph.nodes()` has been deprecated in favor of `graph.iterNodes()`. If you want a list of the nodes of a graph `g` you can use:
```
listOfNodes = [x for x in g.iterNodes()]
```

**Comment by chroeseler** [comment]
Thank you. 
Yeah makes definitely sense.

Vg
