### ISSUE TITLE
MissingDependencyError: Optional dependency tabulate is not installed

### ISSUE THREAD

**Issue by janvekarnaveed** [networkit/networkit#570]
I am running the following command in my jupyter notebook - 
plmCommunities = nk.community.detectCommunities(G, algo=nk.community.PLM(G, True))

Returns error - 
MissingDependencyError                    Traceback (most recent call last)
<ipython-input-37-e7910d8fb536> in <module>()
      1 # Choose and initialize algorithm
----> 2 plmCommunities = nk.community.detectCommunities(G, algo=nk.community.PLM(G, True))

~/anaconda3/envs/python3/lib/python3.6/site-packages/networkit/community.py in detectCommunities(G, algo, inspect)
     49         if inspect:
     50                 print ("solution properties:")
---> 51                 inspectCommunities(zeta, G)
     52         return zeta
     53 

~/anaconda3/envs/python3/lib/python3.6/site-packages/networkit/community.py in inspectCommunities(zeta, G)
     58 	"""
     59         if not have_tabulate:
---> 60                 raise MissingDependencyError("tabulate")
     61         communitySizes = zeta.subsetSizes()
     62         mod = Modularity().getQuality(zeta, G)

MissingDependencyError: Optional dependency tabulate is not installed

**Comment by hmeyerhenke** [comment]
Sounds like you need to install tabulate:
pip3 install tabulate

**Comment by janvekarnaveed** [comment]
Thanks hmeyerhenke it worked. I had earlier installed tabulate using pip instead of pip3 which caused the issue.
