### ISSUE TITLE
Slow computation of shortest paths

### ISSUE THREAD

**Issue by NicolasGensollen** [networkit/networkit#573]
Hello,

I am currently working on a project where I have to maintain dynamic graphs. Nodes and links appear and disappear in time, such that it is more convenient to index all possible nodes at first, and then delete and restore nodes as they arrive or leave. This is because I have a lot of other data structures relying on node indices and I need them to remain the same.

In addition, I have to perform shortest path computations from a source node to the other nodes present in the graph at the time. Running some tests, I found *NetworKit* to be unexpectedly slow when computing the shortest paths.

I suspect that this is related to having all nodes indexed, although only a small portion is present most of the time. To verify this, I made the following test where I create 3 graphs with 10⁴, 10⁵, and 10⁶ possible nodes, but they all have the same edges between the first 100 nodes. I then run various methods to compute shortest paths between node 0 and nodes 1...99. I was expecting the computation times to be more or less the same for the three graphs since they have the exact same set of edges, but the computation time seems to increase for all methods.

Am I missing something here?

Thanks!

Test:  

```python
import random
import networkit as nk
from networkit.distance import AStar, BidirectionalDijkstra, BFS, BidirectionalBFS
```

## Networkit

Create 3 graphs:

- G1 with $10^4$ nodes
- G2 with $10^5$ nodes
- G3 with $10^6$ nodes

G1, G2, and G3 have the exact same edges only between the first 100 nodes, meaning that the remaining nodes are isolated.

We compute the shortest path between node 0 and nodes $1...99$ in G1, G2, and G3 and compare the computation times.

```python
# Initialize the Graphs
G1 = nk.Graph()
G2 = nk.Graph()
G3 = nk.Graph()

# Add the nodes...
for n in range(10**4):
    G1.addNode()
    G1.removeNode(n)
for n in range(10**5):
    G2.addNode()
    G2.removeNode(n)
for n in range(10**6):
    G3.addNode()
    G3.removeNode(n)
    
# Add the edges in Erdos-Renyi fashion
for n1 in range(10**2-1):
    G1.restoreNode(n1)
    G2.restoreNode(n1)
    G3.restoreNode(n1)
    for n2 in range(n1+1,10**2):
        G1.restoreNode(n2)
        G2.restoreNode(n2)
        G3.restoreNode(n2)
        if random.random() <= 0.05:
            G1.addEdge(n1,n2)
            G2.addEdge(n1,n2)
            G3.addEdge(n1,n2)
```

```python
print(G1.numberOfNodes(), G1.upperNodeIdBound())
print(G2.numberOfNodes(), G2.upperNodeIdBound())
print(G3.numberOfNodes(), G3.upperNodeIdBound())
```

    5049 10000
    5049 100000
    5049 1000000

### Bidirectional BFS

Time computation for G1 using Bidirectional BFS:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalBFS(G1,source=0,target=v,storePred=False)
    sp.run()
    sp.getHops()
```

    164 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Time computation for G2 using Bidirectional BFS:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalBFS(G2,source=0,target=v,storePred=False)
    sp.run()
    sp.getHops()
```

    326 µs ± 5.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Time computation for G3 using Bidirectional BFS:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalBFS(G3,source=0,target=v,storePred=False)
    sp.run()
    sp.getHops()
```

    1.97 ms ± 6.26 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### BFS

Time computation for G1 using BFS:

```python
%%timeit
for v in range(10**2):
    sp = BFS(G1,source=0,storePaths=False,target=v)
    sp.run()
    sp.distance(v)
```

    474 µs ± 2.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Time computation for G2 using BFS:

```python
%%timeit
for v in range(10**2):
    sp = BFS(G2,source=0,storePaths=False,target=v)
    sp.run()
    sp.distance(v)
```

    3.18 ms ± 63.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Time computation for G3 using BFS:

```python
%%timeit
for v in range(10**2):
    sp = BFS(G3,source=0,storePaths=False,target=v)
    sp.run()
    sp.distance(v)
```

    37 ms ± 833 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

### A*

Time computation for G1 using Astar:

```python
%%timeit
for v in range(10**2):
    sp = AStar(G1,heu=[0 for _ in range(G1.upperNodeIdBound())],source=0,target=v)
    sp.run()
```

    38.1 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Time computation for G2 using Astar:

```python
%%timeit
for v in range(10**2):
    sp = AStar(G2,heu=[0 for _ in range(G2.upperNodeIdBound())],source=0,target=v)
    sp.run()
```

    377 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Time computation for G3 using Astar:

```python
%%timeit
for v in range(10**2):
    sp = AStar(G3,heu=[0 for _ in range(G3.upperNodeIdBound())],source=0,target=v)
    sp.run()
```

    4.03 s ± 59.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### Dijkstra

Time computation for G1 using Dijkstra:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalDijkstra(G1,source=0,target=v)
    sp.run()
```

    1.95 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Time computation for G2 using Dijkstra:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalDijkstra(G2,source=0,target=v)
    sp.run()
```

    17 ms ± 2.44 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

Time computation for G3 using Dijkstra:

```python
%%timeit
for v in range(10**2):
    sp = BidirectionalDijkstra(G3,source=0,target=v)
    sp.run()
```

    1.79 s ± 83.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Computations on G2 are 10 times slower than on G1, and 10 times slower on G3 than on G2.

```python

```

**Comment by avdgrinten** [comment]
It could very well be that computations are not optimized for situations where `numberOfNodes()` << `upperNodeIdBound()`. That is a valid use case, however. Some slowdown is expected but it should not be linear.

Do you experience the same issue on real-world data sets? Or is the effect less pronounced on real instances? (I'm asking since that would exclude peculiarities of the random graph model that you used above.)

If there is a huge slow down even on real-world graph, one possibility would be to temporarily remap IDs before running an algorithm. Whether that is worth it or not depends on the running time of the SSSP algorithm though.

**Comment by avdgrinten** [comment]
One issue of the generator here is that the graphs have *much* fewer edges than IDs, hence the algorithm will do almost no "useful" work - almost all of the time will be spent on bookkeeping (i.e., clearing out result vectors etc.).

Could you give a few more details on your application? How many nodes / edges do you have in comparison to IDs?

**Comment by NicolasGensollen** [comment]
Thanks for your reply @avdgrinten 

The goal of the application is to analyze large sequences of interactions (financial transactions, IP packets exchanges, phone calls...). The data is basically a list of `t u v` triplets meaning that `u` interacts with `v` at time `t`. Typically, the datasets we study have hundreds of millions (sometimes billions) interactions and a few tens of millions nodes.

When parsing these streams, I maintain static aggregated graphs computed on moving windows (for example the last X interactions, or over the last Y minutes...). So, for each new interaction, I perform so nodes/edges deletions (the old ones that are now out of the windows), and I add a new link. So the number of links in these graphs depends on the size of the windows, the kind of data, the presence of activity peaks and so on. But most of the time, it is very small compared to the number of interactions, the number of possible links, or the number of IDs (`numberOfNodes()` << `upperNodeIdNound()`). For instance, the number of IDs can be 1 million, and the graphs will never have more than a few thousands edges at most.

Then I compute my shortest path features on these graphs. In other words, I do these computations for each interaction in the stream. Without setting the IDs first, I would have to re-index everything for every new interaction and update my other data structures to reflect the new ids, which is prohibitive.

**Comment by NicolasGensollen** [comment]
I'm wondering if this is where things go wrong:

https://github.com/networkit/networkit/blob/d8e952f1e4d5e2758e4744e7c6ea7429a59c7cdf/networkit/cpp/distance/BFS.cpp#L18-L27

`distances` is initialized as a vector of `infDist` and is sized according to `G->upperNodeIdBound()`.

**Comment by avdgrinten** [comment]
Yes, that's what I assume, too. On the other hand, it is not easy to fix since NetworKit relies on this array for a fast implementation of the algorithm.

Try the following instead: dynamically map your node IDs to/from NetworKit node IDs while re-using old IDs. Something like:
```py
# Maps of node IDs to/from NetworKit nodes.
node_to_nk = np.full(10000000, -1, dtype=int)
nk_to_node = np.full(10000000, -1, dtype=int)

s = [] # Stack of unused NetworKit IDs.

def allocNk(node):
	if s:
		i = s.pop()
		G.restoreNode(i)
	else: # Only get a new NetworKit node if we need to.
		i = G.addNode()
	node_to_nk[node] = i
	nk_to_node[i] = node
	return i

def freeNk(node):
	i = node_to_nk[node]
	G.removeNode(i)
	node_to_nk[node] = -1
	nk_to_node[i] = -1
	s.append(i)
```

**Comment by NicolasGensollen** [comment]
Thanks @avdgrinten ! 
I had to modify my code a little bit, but this seems to work well in my settings.
