### ISSUE TITLE
Setting the number of OpenMP threads doesn't seem to affect performance

### ISSUE THREAD

**Issue by enourbakhsh** [networkit/networkit#579]
I migrated from `igraph` to `networkit` to take advantage of its parallelism in finding connected components of huge graphs. I ran the following snippet first with `num_threads = 1` and then with `num_threads = 8` and `num_threads = 16`.  There was no noticeable difference in running time between the three. Am I missing something?

``` python
import networkit as nk
import numpy as np

def get_cc(edges, num_nodes, num_threads):
    nk.setNumberOfThreads(num_threads)
    G = nk.Graph(num_nodes, directed=False)    
    for edge in edges:
        G.addEdge(*edge)
    cc = nk.components.ConnectedComponents(G)
    cc.run()
    return cc.getComponents()

np.random.seed(0)
n = 10_000_000
a = np.random.randint(n//1.8, size=n)
b = np.random.randint(n//1.3, size=n)

edges = zip(a,b)
num_nodes = max(a)+max(b) # apparently it doesn't automatically detect the possible number of nodes?
num_threads = 16

%timeit res = get_cc(edges, num_nodes, num_threads)
```

**Timing results:**

`num_threads = 1`: 1.99 s ± 20.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
`num_threads = 8`: 2.08 s ± 34.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
`num_threads = 16`: 2.07 s ± 40.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

I later checked some values:
``` python
nk.setNumberOfThreads(5)
nk.getMaxNumberOfThreads()
```
> 5

``` python
nk.getCurrentNumberOfThreads()
```
> 1

Does this imply anything? I don't know why the current number of threads should be 1 after I ask for 5 for example.

**Comment by angriman** [comment]
The implementation of `ConnectedComponents` does not use multithreading, you can try to use `ParallelConnectedComponents`.

**Comment by enourbakhsh** [comment]
Thanks @angriman, I tried it but it throws the following error (maybe I don't need `.getComponents()`?):
>AttributeError: 'networkit._NetworKit.ParallelConnectedComponents' object has no attribute 'getComponents'

Is there a similar multithreading feauture in `addEdge(...)` that creates the graph?

On a related note regarding performance, it looks like users are forced to provide the number of nodes in `nk.Graph(...)` before adding the edges which leads to creating unnecessary isolated nodes that wouldn't be important in the calculation of  connected components in my case. Is it possible for `networkit` to infer that information while using `G.addEdge(...)`?

**Comment by angriman** [comment]
Il looks like `.getComponents()` has not been exposed to Python. It should not be too hard to do that, in the meanwhile you can use `.getPartition()`, which returns a `Partition` object (more about that [in the docs](https://networkit.github.io/dev-docs/python_api/networkit.html#networkit.Partition)).

There is no such a feature to create the graph from an edge list in parallel. If you are dealing with large graphs I suggest you to store them in binary files using `NetworkitBinaryWriter` and read them with `NetworkitBinaryReader`.

Nodes in NetworKit are _always_ a continuous sequence from 0 to n-1; if your graph has many isolated nodes that you do not want to include while computing the connected components you can always create a mapping from the nodes in your original graph to nodes in the NetworKit graph.

**Comment by enourbakhsh** [comment]
I looked at the docs - does that mean I can get the connected components of the whole graph from the `Partition` object without much overhead? If so, I'll need to work on figuring it out.

There are cases where I have 80% isolated nodes. The docs is not clear about how to create the mapping in python. Is there any example I can look at?

Also, is it fine that `nk.getCurrentNumberOfThreads()` returns 1 no matter what I set as the number of threads (e.g. `nk.setNumberOfThreads(5)`) ?

**Comment by fabratu** [comment]
We have a rework of the python mapping in the pipeline (nearly finished!). After this is merged, we can get more into details how to expose a function.

**Comment by cruyffturn** [comment]
@enourbakhsh 
>  I don't know why the current number of threads should be 1 after I ask for 5 for example.

I think that's the normal behavior. The following link states that one can only get the correct number in a parallel code:

[](https://stackoverflow.com/questions/8969748/set-number-of-threads-using-omp-set-num-threads-to-2-but-omp-get-num-threads)
