### ISSUE TITLE
Make ConnectedComponents.getPartition() return a const&

### ISSUE THREAD

**Issue by rionda** [networkit/networkit#593]
(Similar to #582) 

https://github.com/networkit/networkit/blob/02de60d064527410c0acf8e1c8cb0d403c5c1409/networkit/cpp/components/ConnectedComponents.cpp#L62

It seems much more reasonable to make this function return a `const&`, as the user is unlikely to want to modify the `Partition` object, and if they do, they should pay the price for their decision. 

There are probably similar issues in the other `ConnecteComponents`-like classes in the `components` module, I did no t check.

**Comment by angriman** [comment]
This has been addressed in #578.
