### ISSUE TITLE
Make Partition.forEntries take a reference as argument

### ISSUE THREAD

**Issue by rionda** [networkit/networkit#594]
https://github.com/networkit/networkit/blob/02de60d064527410c0acf8e1c8cb0d403c5c1409/include/networkit/structures/Partition.hpp#L295

This function, and the similar `parallelForEntries` should likely take a reference `Callback &` to give more flexibility to the caller.

**Comment by fabratu** [comment]
Thanks for the suggestion @rionda. Can you maybe elaborate more (or give examples) why this would be beneficial?

**Comment by avdgrinten** [comment]
In particular, this might introduce another indirection in a critical code path if the compile decides not to inline this function.

**Comment by rionda** [comment]
Having a reference would allow the caller to save and retrieve state/results from the `Callback` object.

**Comment by avdgrinten** [comment]
Sure but is that really important? The callback can just store a reference / pointer to some external data structure. I don't think the cost of the reference outweights the benefits.

**Comment by rionda** [comment]
Ok, whatever, I thought it would be more useful that way =)

**Comment by fabratu** [comment]
Closing this for now. If there is more / new input, we may open this again in the future.
