### ISSUE TITLE
ERROR: NetworKit compilation requires cmake

### ISSUE THREAD

**Issue by DeepaMahm** [networkit/networkit#597]
I'm trying to install Networkit in WSL and I  get the following error

  
```
ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ht4wsfvm/networkit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ht4wsfvm/networkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-07lxmeu3
             cwd: /tmp/pip-install-ht4wsfvm/networkit/
        Complete output (1 lines):
        ERROR: NetworKit compilation requires cmake.
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


```
I first tried on Windows, the same error occurred and I tried in WSL. I'm facing the same problem

Suggestions on how to resolve this issue will be helpful

**Comment by angriman** [comment]
Hi, it looks like you don't have cmake installed.

**Comment by DeepaMahm** [comment]
@angriman 

Thank you, I have installed cmake now. Unfortunately, networkit installatrion isn't successful yet

```
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q9hho1kv/networkit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q9hho1kv/networkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4ixx5vgr/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/deepa/.local/include/python3.7m/networkit Check the logs for full command output.
d
```

Could you please suggest how this can be resolved?

**Comment by DeepaMahm** [comment]
@angriman This is a polite reminder

**Comment by angriman** [comment]
One suggestion is to make sure that you have installed [all the required software](https://github.com/networkit/networkit#requirements). @fabratu any further suggestions about this?

**Comment by DeepaMahm** [comment]
@angriman 

I've checked the requirements

Could you please have a look at the complete log file [uploaded here](https://github.com/DeepaMahm/misc/blob/master/error.txt)?

**Comment by fabratu** [comment]
Hi,

thanks for the log. From this I would say you are missing the dev-headers for Python. If you are using an Ubuntu/Debian based WSL, install ist via:
```
sudo apt-get install python3-dev
```

**Comment by DeepaMahm** [comment]
@fabratu Thank you so much. I'd like to keep everyone posted that the installation was successful after installing dev-headers.

**Comment by fabratu** [comment]
Closing this issue now. The requirements now include python3 headers.
