### ISSUE TITLE
Adding multiple edge weights from networkx graph to networkit

### ISSUE THREAD

**Issue by DeepaMahm** [networkit/networkit#599]
Hello Everyone, 

This is a follow up to my question posted [here](https://stackoverflow.com/questions/64131201/methods-for-generating-complex-network/64150221#64150221)
```
import networkit as nk
import random
import networkx as nx
import matplotlib.pyplot as plt
G = nx.gnm_random_graph(20, 30, seed=1)

for (u, v) in G.edges():
    G.edges[u, v]['weight'] = random.randint(0, 10)

nx.draw(G, with_labels=True)
plt.show()
print(G.edges(data=True))

# Networkx graph to NetworKit graph
G_nk = nk.nxadapter.nx2nk(G, weightAttr='weight')
```
helps in converting a nx graph to nk. However, I am not sure how multiple `weightAttr` has to be added. 
For example,
```
G = nx.gnm_random_graph(20, 30, seed=1)

for (u, v) in G.edges():
    G.edges[u, v]['weight1'] = random.randint(0, 10)
    G.edges[u, v]['weight2'] = random.randint(0, 10)

G_nk = nk.nxadapter.nx2nk(G, weightAttr=['weight1', 'weight2']) # this isn't possible.
print(G_nk.weight(u=0, v=12)) # in networkx I do G.edges(data=True) prints all attributes

```

I would be happy to know if there are alternate ways to add multiple edge attributes.

**Comment by angriman** [comment]
Right now multiple edge attributes are not supported, we have plans to provide such a feature in the future.

**Comment by hmeyerhenke** [comment]
With edge indexing, one could have several vectors within the algorithm to store several weights -- all indexed with the same index. Isn't that right, @angriman? The data structure itself does not support this as a built-in feature.

**Comment by angriman** [comment]
True, with indexing one can always store additional node/edge attributes externally.
