### ISSUE TITLE
Edge centrality

### ISSUE THREAD

**Issue by DeepaMahm** [networkit/networkit#614]
Hi All,

I have been reading through the notes on node `Centrality` available [here](https://github.com/networkit/networkit/blob/Dev/notebooks/Centrality.ipynb). I would like to know if implementations of edge centrality measures are available. For instance, after I delete an edge and use k-core to remove nodes with degree < 2, I would like to see the deletion of which edge leads to the removal of more nodes.

**Comment by hmeyerhenke** [comment]
Edge centrality measures exist, e.g. spanning edge centrality. I don't think what you ask in terms of dynamic k-core is possible so far.
