### ISSUE TITLE
graph: Strange mismatch when loading **reordered** egdelists

### ISSUE THREAD

**Issue by Pzoom522** [networkit/networkit#621]
Hi,

I observed a very strange phenomenon recently. Two egdelists [file1](http://staffwww.dcs.shef.ac.uk/people/x.peng/tmp/file1.txt) and [file2](http://staffwww.dcs.shef.ac.uk/people/x.peng/tmp/file2.txt) store the **same** directed graph in different edge orders (i.e., row orders). I respectively loaded these two files and performed BFS, expecting identical results:

```python
import networkit as nk
nk.setNumberOfThreads(48) # cpu core num

reader = nk.graphio.EdgeListReader(" ", 0, directed=True)
g1 = reader.read("file1.txt")
g2 = reader.read("file2.txt")

result1 = []
nk.graph.Traversal.BFSfrom(g, 0, lambda u, d: result1.append(u))
result2 = []
nk.graph.Traversal.BFSfrom(g, 0, lambda u, d: result2.append(u))
```

However, when comparing the obtained lists, I found that that they differ slightly at one specific location. To be more concrete, while `result1` contains `..., 9634, 9658, *9682*, 9706, 9730, 9754, 9778, 8928, 8933, ...`, the sequence becomes `..., 9634, 9658, 9706, 9730, 9754, 9778, *9682*, 8928, 8933, ...` in `result2`. I guess there must be something wrong when reading & creating the graphs, but  what is it?

Many thanks!

**Comment by Pzoom522** [comment]
FYI, this my code to check whether two files share the 100% same group of edges:

```python
def get_edge_set(fn):
    with open(fn, 'r') as f:
        edgeLines = f.readlines()
    edgeSet = set()
    for line in edgeLines:
        edgeSet.add(line.strip())
    return edgeSet

set1 = get_edge_set("file1.txt")
set2 = get_edge_set("file2.txt")

print(set1 - set2, set2 - set1) # set() set()
```

**Comment by hmeyerhenke** [comment]
The BFS sequences can be in a different order when the graph is stored in a different order -- that's to be expected.

Or do I misinterpret what you call "result"?

**Comment by Pzoom522** [comment]
> The BFS sequences can be in a different order when the graph is stored in a different order -- that's to be expected.
> 
> Or do I misinterpret what you call "result"?

Thanks for replying. My question is that, although two edgelists store edges in different orders,  they represent the same set of node-edge-node triples. Therefore, they should lead to the exactly same graph. In this case, I think it's really wired that the BFS results vary.

**Comment by hmeyerhenke** [comment]
They should lead to the same graph, yes. But a BFS can visit two isomorphic graphs in different orders, leading to different BFS trees. That's not NetworKit-specific.

**Comment by Pzoom522** [comment]
I see your point. That's very helpful! Many thanks.
