### ISSUE TITLE
Potential data races

### ISSUE THREAD

**Issue by tamugang** [networkit/networkit#622]
Hi, we found three potential races in this project, with a static analysis tool we are currently developing. These races do not seem severe issues, but we think it's still good to report them.

### Race on `totalCandidates`

/home/networkit/networkit/cpp/generators/HyperbolicGenerator.cpp:244: A variable defined here could be accessed by multiple threads simultaneously without correct synchronizations.

 244|    count totalCandidates = 0;

This is the OpenMP section causing the race (networkit/cpp/generators/HyperbolicGenerator.cpp:246):

```C++
count totalCandidates = 0;
    #pragma omp parallel for
    for (omp_index i = 0; i < static_cast<omp_index>(n); i++) {
        vector<index> near;
        totalCandidates += quad.getElementsProbabilistically(HyperbolicSpace::polarToCartesian(angles[i], radii[i]), edgeProb, anglesSorted, near);
        for (index j : near) {
            if (j >= n) ERROR("Node ", j, " prospective neighbor of ", i, " does not actually exist. Oops.");
            if (j > i) {
                result.addHalfEdge(i, j);
            }
        }

    }
```

This is not a reduction parallel loop, so the `+=` operator on `totalCandidates` causes races. It seems this variable is only used for debug purpose though.

### Race on `queued`

/home/networkit/networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp:80: A variable defined here could be accessed by multiple threads simultaneously without correct synchronizations.

 80|    bool queued = true;

This is the OpenMP section causing the race (networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp:88):

```C++
#pragma omp parallel for schedule(guided)
        for (omp_index v = 0; v < static_cast<omp_index>(activeNodes.size()); ++v) {
            if (!activeNodes[v]) continue;
            index tid = (index)omp_get_thread_num();

            for (count j = 0; j < k; j++) {
                // and to all previous neighbors of all its neighbors
                G->forNeighborsOf(v, [&](node u) {
                    mCurr[v][j] |= mPrev[u][j];
                });
            }
            // the least bit number in the bitmask of the current node/distance that has not been set
            double b = 0;
            for (count j = 0; j < k; j++) {
                for (count i = 0; i < lengthOfBitmask; i++) {
                    if (((mCurr[v][j] >> i) & 1) == 0) {
                        b += i;
                        break;
                    }
                }
            }
            // calculate the average least bit number that has not been set over all parallel approximations
            b = b / k;
            // calculate the estimated number of neighbors where 0.77351 is a correction factor and the result of a complex sum
            count estimatedConnectedNodes = (count)round(pow(2,b) / 0.77351);
            localEstimatesSum[tid] += estimatedConnectedNodes;
            //std::cout << "(" << v << ", " << estimatedConnectedNodes << ")\t";

            // check whether all k bitmask for this node have reached their highest possible value
            bool nodeFinished = true;
            for (count j = 0; j < k; j++) {
                if (mCurr[v][j] != highestCount[j]) {
                    nodeFinished = false;
                    break;
                }
            }
            // if the node wont change or is connected to enough nodes it must no longer be considered
            if (nodeFinished) {
                localSumRemoved[tid] += estimatedConnectedNodes;
                activeNodes[v] = 0;
            } else {
                queued = true;
            }
        }
```
Depending on the contents of `mCurr` and `highestCount[j]`, there could be concurrent writes to `queued` without synchronizations. It's hard to confirm it statically. So we think it's potentially a race.

### Race on `os_stack_trace_getter_`

In networkit/cpp/graph/test/GraphGTest.cpp:2034:
```C++
        graph->parallelForEdges([&](node, node, edgeweight ew, edgeid eid) {
            EXPECT_NE(none, eid);
            EXPECT_LT(eid, graph->upperEdgeIdBound());
#pragma omp atomic
            m++;
#pragma omp atomic
            sum += ew;
        });
```
`EXPECT_NE` will eventuall call into the below function:
```C++
OsStackTraceGetterInterface* UnitTestImpl::os_stack_trace_getter() {
  if (os_stack_trace_getter_ == NULL) {
#ifdef GTEST_OS_STACK_TRACE_GETTER_
    os_stack_trace_getter_ = new GTEST_OS_STACK_TRACE_GETTER_;
#else
    os_stack_trace_getter_ = new OsStackTraceGetter;
#endif  // GTEST_OS_STACK_TRACE_GETTER_
  }

  return os_stack_trace_getter_;
}
```
Since `parallelForEdges` runs in parallel using OpenMP, there could be concurrent reads/writes to `os_stack_trace_getter_`. Since `os_stack_trace_getter_` points to a heap object, it's also possible that another thread reads that `os_stack_trace_getter_` has been assigned to a heap allocation, but the resource has not finished initializing yet (depending on the instruction order generated by the compiler), and this pointer will be returned and used, which causes undefined behavior.

We are not sure if there is any initialization to this pointer before this parallel loops (we didn't find any calls to `set_os_stack_trace_getter` for this initialization purpose in this project though) or if gtest can already handle it well (again we didn't find potential code to handle this in gtest though), it is possible that it is a race.

**Comment by hmeyerhenke** [comment]
Interesting, thanks for sharing. We'll look into that when the time allows. (Also seems the races found are of different severity.)
