### ISSUE TITLE
Infinite loop when samples are too big

### ISSUE THREAD

**Issue by darabos** [networkit/networkit#633]
If you run PivotMDS or ApproxCloseness with a sample size that is greater than the size of the graph, the sampling code will run in an infinite loop.

- https://github.com/networkit/networkit/blob/7.1/networkit/cpp/viz/PivotMDS.cpp#L105
- https://github.com/networkit/networkit/blob/7.1/networkit/cpp/centrality/ApproxCloseness.cpp#L68

I don't think that's great, but I'm not sure what would be the right fix.

- EstimateBetweenness will just sample the same node multiple times. (https://github.com/networkit/networkit/blob/7.1/networkit/cpp/centrality/EstimateBetweenness.cpp#L33)
- Another option is to throw an exception.
- We could just use a smaller sample.

I think the smaller sample is the most user-friendly option. Maybe I could add a utility function for picking a sample and use that everywhere? It could switch to randomly _discarding_ nodes when the requested sample size is more than half the node count. (So when the requested sample size is greater than the number of nodes this would just finish immediately and return all nodes.)

I know that a sample should generally be way smaller than the whole graph. But I think a reasonable use case is to use a fixed sample size that you expect gives good general performance, like 100. Your code processes a bunch of graphs. One day it hits a graph that has less than 100 nodes and 💥  fails.

**Comment by avdgrinten** [comment]
Thank you for the report. Yes, running into an infinite loop is certainly undesirable. A pragmatic fix would clamp the sample size to the graph size. In the case of closeness, that should yield an exact result. I am not sure what happens in the case of PivotMDS. As you mentioned, other algorithms do not care about drawing multiple identical samples, so they should be fine.

**Comment by Relux-the-Relux** [comment]
Solved by the merge of #724
