### ISSUE TITLE
Definition of neighbor inclusion in GraphTools::subgraphFromNodes unclear

### ISSUE THREAD

**Issue by michitux** [networkit/networkit#651]
When I read the documentation of the method `GraphTools::subgraphFromNodes`, I understand that enabling the neighbor inclusion options will simply include outgoing or incoming neighbors into the induced subgraphs. However, this is not the case. Instead, only edges between the originally given nodes and the neighbors are included but not edges between the neighbors. What surprised me even more is that if just outgoing neighbors shall be included, incoming edges from these neighbors to the original nodes are included, too (and vice-versa if just incoming neighbors shall be considered). Is this whole behavior intentional? If yes, the documentation should be changed to describe it. Currently it says that the method "Returns an induced subgraph of the input graph", which is certainly wrong when any of the neighbor inclusion options is true as edges between the neighbors are missing.

**Comment by michitux** [comment]
I just found #373 which contained a much longer documentation of the methods that describes the current behavior which is apparently intentional. I suggest to restore the longer description from #373.

**Comment by avdgrinten** [comment]
Restoring a longer description is of course a good idea.

To be honest, that functionality is so specific that it is probably better to move it to its own function.
