### ISSUE TITLE
Case configuration in clang-tidy

### ISSUE THREAD

**Issue by michitux** [networkit/networkit#653]
While trying to fix the case of variable names, I noticed that the configuration provided in `.clang-tidy` is not consistent with the style guide. In particular, at least `MemberCase`, `ParameterCase` and `VariableCase` should be `camelBack` according to the style guide and not `CamelCase` as in the configuration. It would be nice if the configuration was consistent with the style guide such that new code could be checked and corrected using clang-tidy by manually enabling the checks on the command line and including only the headers that shall be changed. I suspect that globally adapting the style introduces too many changes but this could of course also be considered as an option, then the checks could be enabled by default.

**Comment by avdgrinten** [comment]
Yes, these `.clang-tidy` settings should be fixed, agreed.

**Comment by angriman** [comment]
Those checks do not even throw warnings, that's because we do not have the `readability-identifier-naming` enabled. I'll fix that.

**Comment by angriman** [comment]
The case configuration for clang-tidy has been fixed, I am closing this.
