### ISSUE TITLE
BUG: EdgeListReader Error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by XikunHuang** [networkit/networkit#725]
**Describe the bug**
Use EdgeListReader to read tab-separated graph file and get Segmentation fault (core dumped) error. 
I encoutered this error in networkit **v7.1, v8.0 and v8.1**. And v7.0 is fine.   

**Environment**
 - OS: Ubuntu18.0.4
 - Networkit Version: 7.1, 8.0, 8.1
 - Python Version: 3.9.2

**To Reproduce**
1. Toy graph file
```
1    2
3    4
5    6
5    8
6    10
```

2. Source code 
```
import networkit as nk

filepath = "./input/toy_graph"
net_reader = nk.graphio.EdgeListReader(separator='\t', firstNode=1, continuous=False, directed=True)
net = net_reader.read(filepath)
print(net.numberOfNodes(), net.numberOfEdges())
```
3. Full error output
Segmentation fault (core dumped)

I also tried the method in [How to read an edge list file?](https://lists.ira.uni-karlsruhe.de/pipermail/networkit/2015-April/000359.html), and it does not work. Any suggestions? 
Thanks a lot.
Xikun

**Comment by angriman** [comment]
Hi Xikun, if you set `continuous=False` then `EdgeListReader` will count the number of unique node ids by creating a map from the node ids in the edge list file to `[0, 1, ..., n - 1]`. Thus, in your case, you just have to remove `firstNode=1`.
Setting `firstNode=1` decreases by 1 the node id of every node in the graph, and this is not meant to be used with `continuous=False`.

**Comment by XikunHuang** [comment]
Hi, angriman, thanks for your quick reply and it really helps.
But simply remove ```firstNode=1``` will raise another error under networkit version 8.0. Based on your comment, I tried 3 ways to read an edge list file with ```continuous=False```, and two of them work. Below are the results.

**Case 1: remove firstNode=1**
```
net_reader = nk.graphio.EdgeListReader(separator='\t', continuous=False, directed=True)
net = net_reader.read(filepath)
print(net.numberOfNodes(), net.numberOfEdges())
for item in net.iterNodes():
   print(item)
```
Error:
```
Traceback (most recent call last):
  File "analysis.py", line 41, in <module>
    net_reader = nk.graphio.EdgeListReader(separator='\t', continuous=False, directed=True)
  File "networkit/graphio.pyx", line 279, in networkit.graphio.EdgeListReader.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (1 given)
```

**Case 2: add firstNode=0**
```
net_reader = nk.graphio.EdgeListReader(separator='\t', firstNode=0, continuous=False, directed=True)
net = net_reader.read(filepath)
print(net.numberOfNodes(), net.numberOfEdges())
for item in net.iterNodes():
   print(item)
```
It works, and output is
8 5
0
1
2
3
4
5
6
7

**Case 3: use readGraph()** 
```
net = nk.readGraph(filepath, nk.Format.EdgeList, separator='\t', firstNode=1, continuous=False, directed=True)
print(net.numberOfNodes(), net.numberOfEdges())
for item in net.iterNodes():
   print(item)
```
It also works and ```firstNode=1```  has no effect. The output is
8 5
0
1
2
3
4
5
6
7

Thanks.
Xikun

**Comment by angriman** [comment]
Thanks for the feedback, about case 1: my bad, `firstNode` is a positional argument of `EdgeListReader` (see [the docs](https://networkit.github.io/dev-docs/python_api/graphio.html#networkit.graphio.EdgeListReader) for more info), and therefore it always needs to be set to some value, in your case 0 would work (as you already did in case 2).
About case 3, if you use `readGraph` with `nk.Format.EdgeList` and `continuous=False`, then `firstNode` is always set to 0.
