### ISSUE TITLE
How to get subgraph with Python

### ISSUE THREAD

**Issue by XikunHuang** [networkit/networkit#770]
In networkit version 5.0, I can get subgraph using **networkit.Graph.subgraphFromNodes()**. But in version 8.1, 
AttributeError: type object 'networkit.graph.Graph' has no attribute 'subgraphFromNodes'. So, how to get subgraph from nodes in networkit 8.1 with python?
Thanks a lot.

**Comment by avdgrinten** [comment]
That function has been moved to `networkit.graphtools` but should still work.

**Comment by XikunHuang** [comment]
> That function has been moved to `networkit.graphtools` but should still work.

Thanks for your quick reply,  **networkit.graphtools.subgraphFromNodes()** works. 
But I can not find the networkit.graphtools module in python [documentation](https://networkit.github.io/dev-docs/python_api/modules.html) of the lastest networkit. However, the c++ documentation contains this module.  I wonder if the python documentation should be updated.
Thanks a lot.

**Comment by fabratu** [comment]
@XikunHuang Thanks for bringing this up. There was indeed a bug in the documentation build. The fix is already in and the module-doc is now available here: https://networkit.github.io/dev-docs/python_api/graphtools.html
