### ISSUE TITLE
nan output for ctd.runSinglePair()

### ISSUE THREAD

**Issue by shash42** [networkit/networkit#776]
I converted a large networkx graph to Networkit to compute commute time distances. Much of the other functionality I tried for sanity checks seems to be working. However, I am running into issues with commute time distance, for eg:

`nkG = nk.nxadapter.nx2nk(G)
print(ctd.runSinglePair(1, 6))`

Nodes 1 and 6 are indeed in the same component, so that should not be an issue. What are some possible reasons to get nan output in networkit commute time distance?

**Comment by avdgrinten** [comment]
Why did you close this issue? Did you find the reason for these `NaN`s?

**Comment by shash42** [comment]
Indeed, it was a really naive mistake. Somehow, I had managed to remove `ctd.run()` and couldn't detect it. Since the code had been working earlier, I thought the issue might be due to some property of the input graph `G`, which I had made some changes to since the last successful run.

**Comment by avdgrinten** [comment]
Alright, thanks for letting us know. There should probably be an error raised when trying to access the pairwise commute distance if the algorithm did not `run()` yet.

**Comment by shash42** [comment]
Hi,

There seems to be a new issue which is very similar. I'm using `ctd.runParallelApproximation()` on a large graph. I am getting `NaN`s on some runs and not on others. I tried varying tolerance between `0.5-10` but all lead to the same behavior. 

I am guessing the non-determinism in `ctd.runParallelApproximation()` could be the reason for this. If so, I guess parallel isn't good for my use case as I don't want my outputs to differ across runs. 

Is any of this expected? Should I stick to `ctd.runApproximation()` for deterministic behavior?
