### ISSUE TITLE
Betweenness scores not shown with Visual Studio Code, but correctly shown if using ipython3 (from terminal)

### ISSUE THREAD

**Issue by limonegiallo** [networkit/networkit#788]
If I run the following code (.py file) from Visual Studio Code, i.e. by pressing the green triangular button "Run Python File in Terminal" at the top right corner of VSCode

`from networkit import *` 
`import networkit as nk`
`import matplotlib.pyplot as plt`
`g = generators.HyperbolicGenerator(1e3).generate()`
`bc = nk.centrality.Betweenness(g)`
`bc.run()`
`bc.ranking()[:10] # the 10 most central nodes`

the expected result (i.e. the betweenness calculation) is NOT shown in the Terminal embedded in VSCode.

The betweenness scores are not displayed either by running the code with `python3 namefile.py` from any Terminal (external to VSCode).

Instead, if I run the same code directly from a Terminal, but using ipython3, the result comes out well:

`Out[4]:`
`[(392, 625118.6896734448),`
 `(875, 204886.97319625755),`
 `(170, 121481.35921722073),`
 `(621, 72627.46666666666),`
 `(566, 71881.75991032101),`
 `(37, 62046.49111887374),`
 `(701, 53157.760291814484),`
`(988, 45316.922735729204),`
 `(934, 42894.204329181564),`
 `(657, 32147.666666666664)]`

**Why? What should I change in Visual Studio Code in order to see my results in its embedded Terminal?
Or by any Terminal, with the command `python3 namefile.py`?**

P.S.: If I add other commands to my code, such as

`print(g.numberOfNodes(), g.numberOfEdges()) `

VSCode shows correctly the results in its embedded Terminal. 
Therefore, it looks like that (so far) only the betweenness-related results are not shown/displayed.

**Comment by avdgrinten** [comment]
What you're experiencing is not a NetworKit issue but just the way Python works: `bc.ranking()` does not print anything. ipython simply prints the result of each statement while vscode does not seem to do that. If you do `print(bc.ranking()[:10])` instead, it should work.

**Comment by limonegiallo** [comment]
@avdgrinten Thanks a lot! 
However, to me, it is interesting to notice that the output is displayed by using `ipython3`, even though not typing any `print` command... I should read/study more about `python` and `ipython`...!
