### ISSUE TITLE
"not a valid Format.SNAP file" using readGraph

### ISSUE THREAD

**Issue by limonegiallo** [networkit/networkit#794]
Hi, I am following the [guidelines](https://networkit.github.io/dev-docs/notebooks/IONotebook.html) to read a graph in the SNAP file format and I am using the following command:
```
G = nk.readGraph("/home/JohnRambo/Documents/myFolder/mygraph.txt",nk.Format.SNAP)
```

If I just use the format with nodes `<u v>` it works. Example:
```
1 2
1 3
1 4
```
If I add the weight, i.e. `<u v w>` it does not work, saying: `mygraph.txt is not a valid Format.SNAP file: Line does not end with line break`. 
Example:
```
1 2 1
1 3 1
1 4 1
```
I tried to add line breaks/separators at the end of each line as `,`, `;`,`\n`,`.`, etc. but still does not work. 

**Any idea on how to fix it?**

**Comment by fabratu** [comment]
If I am not mistaken, the SNAP-file format does not support weighted graphs (also the list of SNAP-files on https://snap.stanford.edu/data/). All weighted graphs have a different format from the usual SNAP. 

The error message could be more specific though for this case.

The way your file is build, you can read it with the EdgeListReader, like described here: https://networkit.github.io/dev-docs/notebooks/IONotebook.html

**Comment by limonegiallo** [comment]
Thanks a lot, I followed your hint and it now works!

I used the following graph with weights (saved as `mygraph_weights.txt`):
```
1 2 1
1 3 1
1 4 1
```
i.e. a graph composed of nodes `1, 2, 3, 4` and edges `(1, 2)`, `(1, 3)` and `(1,4)`, all weights as `1`, and I read it with the following commands:
```
edgeListReader = nk.graphio.EdgeListReader(' ', 1)
G = nk.readGraph("/home/JohnRambo/Documents/myFolder/mygraph_weights.txt", nk.Format.EdgeListTabOne)
```
