### ISSUE TITLE
Wrong betweenness with Networkit?

### ISSUE THREAD

**Issue by limonegiallo** [networkit/networkit#795]
Apparently, both node betweenness and edge betweenness calculated with networkit give different values than what supposed to be.

Lets consider the following undirected graph ([pag. 20/85 in these Lecture notes](http://www2.unb.ca/~ddu/6634/Lecture_notes/Lecture_4_centrality_measure.pdf)), written as edge list and saved in `mygraph.txt`:
```
1 2
1 5
2 3
2 5
3 4
4 5
4 6
```
The node betweenness should be ([pag. 20/85 in these Lecture notes](http://www2.unb.ca/~ddu/6634/Lecture_notes/Lecture_4_centrality_measure.pdf)):
```
Node | Betweenness
1 0
2 1.5
3 1
4 4
5 3
6 0
```

However, by running the following code:
```
from networkit import *  
import networkit as nk 

G = nk.readGraph("/home/JohnRambo/Documents/myFolder/mygraph.txt",nk.Format.SNAP)
G.indexEdges()
btwn = nk.centrality.Betweenness(G, normalized=False, computeEdgeCentrality=True)
btwn.run()
print(btwn.scores()[:10])
print(btwn.edgeScores()[:10])
```
I got these results:
```
node betweenness: [3.0, 0.0, 6.0, 2.0, 9.0, 0.0]
edge betweenness: [4.0, 6.0, 5.0, 7.0, 7.0, 11.0, 10.0]
```
My calculation gives different results (the node betweenness scores are in agreement with those ones shown at [pag. 20/85 in these Lecture notes](http://www2.unb.ca/~ddu/6634/Lecture_notes/Lecture_4_centrality_measure.pdf))
```
node betweenness: [0.0, 1.5, 1.0, 4.5, 3.0, 0.0]
edge betweenness: [2.0, 3.0, 3.5, 2.5, 3.5, 5.5, 5.0]
```
**After a quick comparison I can see that the networkit values of edge betweenness are double than mine and the values of edges `(2,3)` and `(2,5)`, i.e. the values `3.5` and `2.5` (the third and the fourth ones) are switched. About the node betweenness, the networkit's ones are still double than mine, but in a very different order, kind of randomly shuffled?**

**Could you be please clarify?**

**Comment by fabratu** [comment]
For undirected graphs the betweenness centrality is indeed two times of the mathematical description. The reason is, that SSSP-calculation is done for each node and therefore edges are counted twice.

If you use the EdgeListReader for your example also the node are in the correct order:

```
G = nk.readGraph("mygraph.txt", nk.Format.EdgeListSpaceZero)
G.indexEdges()
btwn = nk.centrality.Betweenness(G, normalized=False, computeEdgeCentrality=True)
btwn.run()
print(btwn.edgeScores())
>>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
print(btwn.scores())
>>> [0.0, 3.0, 2.0, 9.0, 6.0, 0.0]
```

**Comment by avdgrinten** [comment]
The Betweenness ranking is not influenced by this factor of 2 for undirected graphs. Does your application really require you to deal with absolute Betweenness values (that's rarely a good idea in my experience), or do you need a ranking?

**Comment by limonegiallo** [comment]
> For undirected graphs the betweenness centrality is indeed two times of the mathematical description. The reason is, that SSSP-calculation is done for each node and therefore edges are counted twice.
> 
> If you use the EdgeListReader for your example also the nodes are in the correct order:
> 
> ```
> G = nk.readGraph("mygraph.txt", nk.Format.EdgeListSpaceZero)
> G.indexEdges()
> btwn = nk.centrality.Betweenness(G, normalized=False, computeEdgeCentrality=True)
> btwn.run()
> print(btwn.edgeScores())
> >>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
> print(btwn.scores())
> >>> [0.0, 3.0, 2.0, 9.0, 6.0, 0.0]
> ```

@fabratu many thanks for your reply and contributor. OK for the node betweenness (I will divide by two all the values). However, the order of the edge betweenness is still not correct.

What you wrote:
```
> print(btwn.edgeScores())
> >>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
```
My calculation:
```
edge betweenness: [2.0, 3.0, 3.5, 2.5, 3.5, 5.5, 5.0]
```
**How to fix it?**

Many thanks :)

**Comment by limonegiallo** [comment]
> The Betweenness ranking is not influenced by this factor of 2 for undirected graphs. Does your application really require you to deal with absolute Betweenness values (that's rarely a good idea in my experience), or do you need a ranking?

@avdgrinten thank you for your comment... I would like to get both absolute and normalised values of both node and edge betweenness...

**Comment by limonegiallo** [comment]
> > For undirected graphs the betweenness centrality is indeed two times of the mathematical description. The reason is, that SSSP-calculation is done for each node and therefore edges are counted twice.
> > If you use the EdgeListReader for your example also the nodes are in the correct order:
> > ```
> > G = nk.readGraph("mygraph.txt", nk.Format.EdgeListSpaceZero)
> > G.indexEdges()
> > btwn = nk.centrality.Betweenness(G, normalized=False, computeEdgeCentrality=True)
> > btwn.run()
> > print(btwn.edgeScores())
> > >>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
> > print(btwn.scores())
> > >>> [0.0, 3.0, 2.0, 9.0, 6.0, 0.0]
> > ```
> 
> @fabratu many thanks for your reply and contribution. OK for the node betweenness (I will divide by two all the values). However, the order of the edge betweenness is still not correct.
> 
> What you wrote:
> 
> ```
> > print(btwn.edgeScores())
> > >>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
> ```
> 
> My calculation:
> 
> ```
> edge betweenness: [2.0, 3.0, 3.5, 2.5, 3.5, 5.5, 5.0]
> ```
> 
> **How to fix it?**
> 
> Many thanks :)

*Hi, any news or ideas in this regard?*

**Comment by fabratu** [comment]
Sorry for the delay.

As you already discovered, the edge betweenness is also twice due to double counting (same argument for undirected graphs).

The order of the result can be confusing and maybe we need more documentation in this regard. The results in `edgeScores` are ordered by edge indices. Edge indices however are not assigned in the same order as you would retrieve the edges with iterators. Therefore you would have to map the scores to the correct edge (iterate one time over all edges).

For your example graph:

```
>>> for e in G.iterEdges():
...     print(e)
...
(0, 1)
(0, 4)
(1, 2)
(1, 4)
(2, 3)
(3, 4)
(3, 5)
```

```
>>> for e in G.iterEdges():
...     print(G.edgeId(e[0], e[1]))
...
0
3
1
4
2
5
6
```

**Comment by hmeyerhenke** [comment]
Double counting is imho the standard view following from the definition, even for undirected graphs. The sum iterates over ordered pairs s and t different from v.

**Comment by limonegiallo** [comment]
> As you already discovered, the edge betweenness is also twice due to double counting (same argument for undirected graphs).
> 
> The order of the result can be confusing and maybe we need more documentation in this regard. The results in `edgeScores` are ordered by edge indices. Edge indices however are not assigned in the same order as you would retrieve the edges with iterators (which is the order of edges in your example). Therefore you would have to map the scores to the correct edge (iterate one time over all edges).
> 
> For your example graph:
> 
> ```
> >>> for e in G.iterEdges():
> ...     print(e)
> ...
> (0, 1)
> (0, 4)
> (1, 2)
> (1, 4)
> (2, 3)
> (3, 4)
> (3, 5)
> ```
> 
> ```
> >>> for e in G.iterEdges():
> ...     print(G.edgeId(e[0], e[1]))
> ...
> 0
> 3
> 1
> 4
> 2
> 5
> 6
> ```

Thank you @fabratu ...Therefore, if I understood correctly, the following results that I got from networkit
```
> print(btwn.edgeScores())
> >>> [4.0, 7.0, 7.0, 6.0, 5.0, 11.0, 10.0]
```
should be sorted according to what you wrote, i.e.:
```
> >>> for e in G.iterEdges():
> ...     print(G.edgeId(e[0], e[1]))
> ...
> 0
> 3
> 1
> 4
> 2
> 5
> 6
> 
```
That would bring to:
```
0 --> 4.0
3 --> 6.0
1 --> 7.0
4 --> 5.0
2 --> 7.0
5 --> 11.0
6 --> 10.0
```
Then, by dividing by 2, we would get what I calculated by hand:
```
(0 -->)  4.0 / 2 = 2.0
(3 -->)  6.0 / 2 = 3.0
(1 -->)  7.0 / 2 = 3.5
(4 -->)  5.0 / 2 = 2.5
(2 -->)  7.0 / 2 = 3.5
(5 -->)  11.0 / 2 = 5.5
(6 -->)  10.0 / 2 = 5.0
```
Many thanks!

**Comment by fabratu** [comment]
Seems that we resolved everything. Closing this issue.
