### ISSUE TITLE
Provide run method in Coarsening Classes that support copy elision

### ISSUE THREAD

**Issue by CxVercility** [networkit/networkit#801]
The current way ParallelPartitionCoarsening works is that the run() method generates the coarsened graph, saves it to a field and then returns it in the getCoarseGraph() method.
Doesn't this prevent copy elision and forcea a complete Graph copy to be made whenever getCoarseGraph() is called?

Since changing the run method's signature would break compatibility (e.g for PLM) I'd propose to add another run function that does the same but returns the graph directly. Functions that depend on that saved Graph would need a Graph reference added to their signature then though.

If there is another possibility to get the graph without a copy that i've overlooked i'll gladly take any advice or other ideas.
Otherwise, i'll glady try to make a pull request for PPC since i already have a working version locally

**Comment by avdgrinten** [comment]
What about adding a method to move the new `Graph` out of the `ParallelPartitionCoarsening` object?

**Comment by CxVercility** [comment]
Not exactly sure how your first idea would work/what youre proposing, `return std::move(Gcoarsened)` wouldnt work because of the const qualifier on Gcoarsened would it? At least that's what my IDE is telling me.

Changing the signature to `Graph& getCoarseGraph()` works fine but I dont know if this will break code in some other place, adding a second function would be safer but it'd also prevent other code from benefitting from this change i suppose

I'm really not smart enough for this kind of stuff so whatever sounds better to you.

**Comment by avdgrinten** [comment]
I think the chance for breaking other users is low. `Graph g = ppc.getCoarseGraph()` and `auto g = ppc.getCoarseGraph()` would both behave as before (and do a copy). Only `Graph g = std::move(ppc.getCoarseGraph())` or strange `decltype`-based codes would break. Overall, I think it's safe to add a non-const overload here (probably in a addition to a const overload that returns a `const Graph &`).

**Comment by CxVercility** [comment]
Unless im misunderstanding you it's not possible to add a second overloaded function here regardless of whether you meant 
`const Graph& getCoarseGraph()` or `const Graph& getCoarseGraph() const` (at least I didnt get that to work lol)

Ill make a pull request that includes the non-const overload for now, if there's more to add that shouldn't be a problem to include later.

**Comment by avdgrinten** [comment]
Thank you for the PR. I meant the latter. Adding a new overload does not work, but changing the existing `getCoarseGraph() const` function to return a `const Graph &` instead of a `Graph` should work. Can you add that to your PR?

**Comment by CxVercility** [comment]
Sure, Ill add it as soon as I get back to my Laptop.
What exactly is the purpose of that change though?

**Comment by avdgrinten** [comment]
By returning a const reference, we can avoid a copy if no modification of the new `Graph` is needed (while the current function always has to create a copy).

**Comment by CxVercility** [comment]
Isn't that already the case with `Graph&` instead of `const Graph&`?
Im a bit stuck up about what adding the const specifier to the reference actually gets us, sorry for the consecutive questions :D
