### ISSUE TITLE
Pre-built wheel packages

### ISSUE THREAD

**Issue by Thijss** [networkit/networkit#814]
Hi there,

The release notes for version 9.0 mention the following:

> . Currently we have no pre-built wheel-package available

Maybe I overlook something very obvious, but I am wondering what is stopping the creation of wheel packages.
Adding wheel packages would greatly decrease installation times I think.

**Comment by fabratu** [comment]
The PR is merged and wheels are now build by the CI. While they are not yet uploaded automatically, you can already download them (available for 31 days for updates on `master`) after a pipeline has finished completely.

Link to the pipeline (click on a finished run-set to download the wheels): https://github.com/networkit/networkit/actions/workflows/build_wheels.yml

I am closing this issue for now. If there are any questions, feel free to open it again.
