### ISSUE TITLE
Finding cycles in the graph

### ISSUE THREAD

**Issue by pauljurczak** [networkit/networkit#851]
I'm scanning the documentation, but I can't find a function to search for cycles (loops) in the graph. There are a bunch of them for self-loops, but I'm looking for multi-node loops. I would appreciate a link.

**Comment by angriman** [comment]
NetworKit does not implement an algorithm to find cycles in a graph. However, if you only need to determine whether a graph has cycles or not, it suffices to check whether the graph is a tree or a forest.  For undirected graphs, this can be done by checking that #of edges equals (#of nodes - #of connected components). For directed graphs: https://github.com/networkit/networkit/issues/816

**Comment by avdgrinten** [comment]
In general, it would be quite time consuming to find all cycles in a graph, as the number of (simple) cycles can grow exponentially in the number of vertices.

**Comment by pauljurczak** [comment]
Thanks. I wanted to make sure I'm not missing something.
