### ISSUE TITLE
Inconsistency among addEdge(), numberOfEdges(), and forEdges()

### ISSUE THREAD

**Issue by XikunHuang** [networkit/networkit#859]
**Describe the bug**
I want to use NetworKit as a C++ library. But there is inconsistency among addEdge(), numberOfEdges(), and forEdges().
It seems that, when adding an edge addEdge(u,v) where **u>upperNodeIdBound()**, we will have:
hasEdge(u,v):False
numberOfEdges():+1
forEdges(): do not index (u,v)

**Environment**
 - OS: CentOS 8.5.2111
 - Networkit Version: 9.0
 - gcc: 8.5
 - C++ Standard: 17

**To Reproduce**

1. Source code 
```
#include <iostream>
#include <networkit/graph/Graph.hpp>
using namespace NetworKit;

int main(int argc, char *argv[])
{
    Graph G(10);
    std::cout << "upperNodeIdBound(): " << G.upperNodeIdBound() << std::endl;
    G.addEdge(1,2);
    G.addEdge(15,2);
    std::cout << "hasEdge(15,2): " << G.hasEdge(15, 2) << std::endl;
    std::cout << "numberOfNodes(): " << G.numberOfNodes() << std::endl;
    std::cout << "numberOfEdges(): "<< G.numberOfEdges() << std::endl;
    std::cout << "Edges: " << std::endl;
    G.forEdges([&] (node u, node v)
               {
        std::cout << u << "," << v << std::endl;
               });
    return 0;
}
```
2. output
```
upperNodeIdBound(): 10
hasEdge(15,2): 0
numberOfNodes(): 10
numberOfEdges(): 2
Edges: 
2,1

```
It is confusing that whether G.addEdge(15,2) succeeds or not.
If it succeeds, hasEdge(15,2) should be TRUE, and forEdges() should index this edge；
If it fails, numberOfEdges() should be 1.  

And I checked the original C++ implementation of **Graph::addEdge**. if addEdge(u,v) where u>upperNodeIdBound, there should be an error. I'm confused that why **assert(u < z);**  does not work in my case.
```
/** EDGE MODIFIERS **/

void Graph::addEdge(node u, node v, edgeweight ew) {
    assert(u < z);
    assert(exists[u]);
    assert(v < z);
    assert(exists[v]);

    // increase number of edges
    ++m;
    outEdges[u].push_back(v);

    // if edges indexed, give new id
    if (edgesIndexed) {
        edgeid id = omega++;
        outEdgeIds[u].push_back(id);
    }

    if (directed) {
        inEdges[v].push_back(u);

        if (edgesIndexed) {
            inEdgeIds[v].push_back(omega - 1);
        }

        if (weighted) {
            inEdgeWeights[v].push_back(ew);
            outEdgeWeights[u].push_back(ew);
        }

    } else if (u == v) { // self-loop case
        if (weighted) {
            outEdgeWeights[u].push_back(ew);
        }
    } else { // undirected, no self-loop
        outEdges[v].push_back(u);

        if (weighted) {
            outEdgeWeights[u].push_back(ew);
            outEdgeWeights[v].push_back(ew);
        }

        if (edgesIndexed) {
            outEdgeIds[v].push_back(omega - 1);
        }
    }

    if (u == v) { // count self loop
        ++storedNumberOfSelfLoops;
    }
}
```

Any suggestions?  Thanks a lot.
Xikun

**Comment by avdgrinten** [comment]
The assertions are not enabled in release builds. I agree that our error reporting should be better here. There have been discussions about changing this in the past; we should probably prioritize this issue in the near future.

**Comment by XikunHuang** [comment]
Thanks for your quick reply. Anyway, the networkit is a cool library and I enjoy using it.
