### ISSUE TITLE
Append or Concatenate Graphs

### ISSUE THREAD

**Issue by carlosg-m** [networkit/networkit#861]
I'm trying to integrate networkit with cluster computing (Spark). 
Is it possible to append multiple graphs?
This would be useful, because it would allow me to create a graph for each partition in the adjacency table in parallel, and then collect all sub-graphs and concatenate them.

**Comment by angriman** [comment]
Sorry for the delay. You are probably looking for something like `GraphTools::append(Graph &G, const Graph &G1)` [1]. It appends the graph `G1` to graph `G`.

[1] https://networkit.github.io/dev-docs/cpp_api/function_GraphTools_8hpp_1a5e481335db685d3ca19eb5631edade99.html

**Comment by carlosg-m** [comment]
I haven't tried it yet, but i believe so. Thank you
