### ISSUE TITLE
Multi-edge indexes not saved correctly in binary format

### ISSUE THREAD

**Issue by opatut** [networkit/networkit#914]
It appears persistence of edge indexes has been merged into `9.1.1` via #751 for #495, but I can't seem to get it to work if there are multiple edges between the same nodes in a graph:

```python
import networkit, pickle

print("Networkit version:", networkit.__version__)

g = networkit.graph.Graph(directed=True, edgesIndexed=True)
g.addNode()
g.addNode()
g.addEdge(0, 1)
g.addEdge(0, 1)
print("Before serialization")
g.forEdgesOf(0, print)

networkit.graphio.writeGraph(g, "a.graph", networkit.Format.NetworkitBinary)
g2 = networkit.readGraph("a.graph", networkit.Format.NetworkitBinary)
print("Read from file")
g2.forEdgesOf(0, print)

print("Unpickled")
g3 = pickle.loads(pickle.dumps(g))
g3.forEdgesOf(0, print)
```

Output is:

```
Networkit version: 9.1.1
Before serialization
0 1 1.0 0
0 1 1.0 1
Read from file
0 1 1.0 0
0 1 1.0 0
Unpickled
0 1 1.0 0
0 1 1.0 0
```

After reading or unpickling, the last column (edge index) gives me 0 only. It appears not to be a problem when I don't add multiple edges between the same nodes, so maybe it's a bug in the implementation?

Thanks for any help.

_Originally posted by @opatut in https://github.com/networkit/networkit/issues/495#issuecomment-1082870053_

**Comment by fabratu** [comment]
Technically multi edges are not supported in NetworKit. However it may be reasonable to be able to store them in binary format. Is there any chance, you might be able to look into it yourself (with help/guidance) and post a PR?

**Comment by fabratu** [comment]
Closed due to inactivity of the issue.
