### ISSUE TITLE
PageRank example is not correct

### ISSUE THREAD

**Issue by ArindamK92** [networkit/networkit#916]
I think the pageRank example in the notebook is not proper. It requires to specify "tol" like below:
nk.centrality.PageRank(K, damp = 0.85, tol = 1e-6)

Right now the example is like below (I hope here 1e-6 is supposed to be the value of "tol", but it is considering damp = 1e-6 actually):
pr = nk.centrality.PageRank(K, 1e-6)

**Comment by angriman** [comment]
Thank you for bringing this up, this can be fixed by removing the tolerance values from the examples -- see #921 .
