### ISSUE TITLE
Inconsistent weights after GraphTools::toUndirected

### ISSUE THREAD

**Issue by angriman** [networkit/networkit#931]
If we pass a directed weighted graph `Gd` with bidirectional edges such as `(u, v, w1)` and `(v, u, w2)` with `w1 != w2` to `GraphTools::toUndirected()`, the resulting undirected graph `Gu` will have inconsistent edge weights. If we traverse the edge `e = (u, v)` in `Gu`, the weight will be `w1`, but if we traverse `e` in the other direction, the weight will be `w2`, which is obviously wrong since `Gu` is undirected.

This happens because the copy constructor of `Graph` (used by `GraphTools::toUndirected`) simply copies the edge weights to the new graph.

**Comment by Relux-the-Relux** [comment]
Which behavior would be desirable here? Should it then become a multigraph or should the edge have a weight of `w1+w2`?

**Comment by angriman** [comment]
I don't think we should generate a multigraph, they are not well-supported in NetworKit. What about taking as input a binary operator? We could use `std::plus` by default.
