### ISSUE TITLE
Wrong TriangleEdgeScore on multi-graphs

### ISSUE THREAD

**Issue by darabos** [networkit/networkit#953]
For example,
```python
import networkit as nk
G = nk.graph.Graph(2)
G.addEdge(0, 1)
G.addEdge(0, 1)
s = nk.sparsification.TriangleEdgeScore(G)
G.indexEdges()
s.run()
print(s.scores())
```
prints
```
[18446744073709551615, 18446744073709551615]
```

ChibaNishizekiTriangleEdgeScore is also wrong, it just outputs zeros for the duplicate edges.
```python
G = nk.graph.Graph(3)
G.addEdge(0, 1)
G.addEdge(0, 1)
G.addEdge(2, 0)
G.addEdge(2, 1)
s = nk.sparsification.ChibaNishizekiTriangleEdgeScore(G)
G.indexEdges()
s.run()
print(s.scores())
```
prints
```
[2, 0, 2, 2]
```

I'm not sure what would be the right fix, just wanted to let you know. Thanks!

**Comment by hmeyerhenke** [comment]
Multigraphs are not guaranteed to be handled correctly throughout many algorithms. (Early on we had to take a decision and agreed not to support multigraphs since they complicate the code and make it slower.) This is not documented well, I agree.

**Comment by fabratu** [comment]
Closing this issue now. We merged a PR that improves the documentation and enables checking for multi edges when inserting edges. Feature will be part of the next release. You can use it right now by installing from the master-branch (or downloading a wheel artifact from CI).
