### ISSUE TITLE
The calculation result of networkit nk.centrality.KatzCentrality algorithm is different from the result of networkx

### ISSUE THREAD

**Issue by wizard0** [networkit/networkit#955]
Hi, I use katz algorithm to caculate nodes' centrality. But the calculation result of networkit nk.centrality.KatzCentrality algorithm is different from the result of networkx. I'm sure there is no difference in the graph I calculated using networkx and networkit and the parameters of the algorithm are the same. Does anyone know what is causing this problem?

```
// networkit code
katz_res = nk.centrality.KatzCentrality(nkgraph, alpha=5e-4, beta=1.0, tol=1e-12)

// networkx code
centrality = nx.katz_centrality(nxgraph, alpha=5e-4, beta=1.0, tol=1e-12)
```

By the way, my code run failed on Ubuntu 20.04:`"networkit.graph.Graph" object has no attribute 'attachNodeAttribute'`. But it can work successfully on MacOS. Should I check the version of networkit on Ubuntu20.04?

**Comment by hmeyerhenke** [comment]
A possible reason could be the direction of the walks (incoming vs outgoing).

**Comment by fabratu** [comment]
> By the way, my code run failed on Ubuntu 20.04:"networkit.graph.Graph" object has no attribute 'attachNodeAttribute'. But it can work successfully on MacOS. Should I check the version of networkit on Ubuntu20.04?

It is likely, that on Ubuntu 20.04 you have a version <10.0 installed. Node attributes were added with release 10.0. See here for more details: https://networkit.github.io/news.html#may-18-2021-networkit-10-0-released

**Comment by fabratu** [comment]
Closing this issue for now. @wizard0: Feel free to reopen if the problem still persists or there are other related questions.
