### ISSUE TITLE
Can't load GraphML file and no matching error message found

### ISSUE THREAD

**Issue by readyready15728** [networkit/networkit#961]
Forgive me if I'm being a n00b here; I usually don't get stumped but in this case I couldn't find any leads. Anyway I'm reading _A First Course in Network Science_ and wanted to load `actors_costar.gml`, which can be found in `datasets/imdb` after cloning the repository:

https://github.com/CambridgeUniversityPress/FirstCourseNetworkScience

Acknowledging the possibility of choking on gzip-compressed files, I tried it anyway and got the following error:

```
In [2]: nk.readGraph('actors_costar.graphml.gz', nk.Format.GML)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File networkit/graphio.pyx:1128, in networkit.graphio.readGraph()

File networkit/graphio.pyx:79, in networkit.graphio.GraphReader.read()

RuntimeError: GML graph file broken

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 nk.readGraph('actors_costar.graphml.gz', nk.Format.GML)

File networkit/graphio.pyx:1126, in networkit.graphio.readGraph()

File networkit/graphio.pyx:1131, in networkit.graphio.readGraph()

OSError: actors_costar.graphml.gz is not a valid Format.GML file: GML graph file broken
```

Very well. I tried unpacking the two files and tried again:

```
In [3]: nk.readGraph('actors_costar.graphml', nk.Format.GML)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File networkit/graphio.pyx:1128, in networkit.graphio.readGraph()

File networkit/graphio.pyx:79, in networkit.graphio.GraphReader.read()

RuntimeError: graph key not found

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 nk.readGraph('actors_costar.graphml', nk.Format.GML)

File networkit/graphio.pyx:1126, in networkit.graphio.readGraph()

File networkit/graphio.pyx:1131, in networkit.graphio.readGraph()

OSError: actors_costar.graphml is not a valid Format.GML file: graph key not found
```

I am new to the subject matter and just don't know how to proceed.

**Comment by fabratu** [comment]
Hi, no problem at all!

The dataset you are referring to is in `GraphML`[1] format, not `GML`[2]. NetworKit does also provide a reader for this format. You were right though about decompression - this have to be done before reading in the file:

```
>>> G = nk.readGraph('actors_costar.graphml', nk.Format.GraphML)
>>> print(G)
NetworKit.Graph(n=252999, m=1015187)
```

[1] https://en.wikipedia.org/wiki/Graph_Modelling_Language
[2] https://en.wikipedia.org/wiki/GraphML

**Comment by readyready15728** [comment]
> Hi, no problem at all!
> 
> The dataset you are referring to is in `GraphML`[1] format, not `GML`[2]. NetworKit does also provide a reader for this format. You were right though about decompression - this have to be done before reading in the file:
> 
> ```
> >>> G = nk.readGraph('actors_costar.graphml', nk.Format.GraphML)
> >>> print(G)
> NetworKit.Graph(n=252999, m=1015187)
> ```
> 
> [1] https://en.wikipedia.org/wiki/Graph_Modelling_Language [2] https://en.wikipedia.org/wiki/GraphML

A truly subtle matter. Thanks for the input.
