### ISSUE TITLE
Core dumped when adding weighted edges with edgesIndexed=True

### ISSUE THREAD

**Issue by rookya** [networkit/networkit#986]
Hello all, first issue here.

Decided I would report the following:
I have a dict mapping strings to node ids as well as a list of edges

    import networkit as nk

    nodes = {'Joe':0, 'Bob': 1, 'Sue': 2}  # 60 nodes approx.
    edges = [
        {"from":0, "to":1, "weight":  0.1231232329}, 
        {"from":1 ,"to": 2, "weight:" 123.413123627)
    ] # 2-3k edges approx.

    G = nk.Graph(n=len(nodes), weighted=True, directed=True, edgesIndexed=True)
    
    for edge in edges:
        G.addEdge(u=edge["from"], v=edge["to"], w=round(edge["weight"], 4))

results in:
    Segmentation fault (core dumped)

Tested the same logic with edgesIndexed=False and haven't yet encountered the core dump.
Also tried groupbyng my data by from, to in order to avoid multiEdges but still receive the error.

Perhaps there is some elementary logical error I'm making due to my lack of understanding in c++ and low-level memory management. Furthermore, this is my first ever issue so please be lenient.

Happy to provide more data as needed.

**Comment by fabratu** [comment]
Hi,

thanks for reaching out. 

I could reproduce the error - it originates from the constructor. If you want indexed edges, create the graph without indexed edges and call G.indexEdges() afterwards.

```
import networkit as nk

nodes = {'Joe':0, 'Bob': 1, 'Sue': 2}  # 60 nodes approx.
edges = [
    {"from":0, "to":1, "weight":  0.1231232329}, 
    {"from":1 ,"to": 2, "weight:" 123.413123627)
] # 2-3k edges approx.

G = nk.Graph(n=len(nodes), weighted=True, directed=True)
G.indexEdges()

for edge in edges:
    G.addEdge(u=edge["from"], v=edge["to"], w=round(edge["weight"], 4))
```
