### ISSUE TITLE
Extending NetworKit more efficiently

### ISSUE THREAD

**Issue by xiaohan2012** [networkit/networkit#99]
I'm currently trying to extend NetworKit by adding code to `networkit/_NetworKit.pyx` directly. 

Then, I run `python setup.py build_ext --inline` to compile the`.pyx` file. 

However, it takes quite some time for this step (~ 10 secs). 

Is there any way to speed up the process?

One way I tried is to separating my code with `_NetworKit.pyx`. 

However, my code depends on some definitions in `_NetworKit.pyx`. I tried to copy them to the new file but the dependency chain seems too long so I gave up. 

Any suggestions?

(Happy holiday! BTW)

**Comment by fabratu** [comment]
Closing this due to being inactive for a long time.
