### ISSUE TITLE
SPSP crashes if unreachable node in target list

### ISSUE THREAD

**Issue by forest-rev** [networkit/networkit#994]
Hi,

When calculating some pairs shortest paths (SPSP) from one node to a set of target nodes, I noticed that if the target node list contains an unreachable node, the algorithm crashes. Running SPSP from the same source node but without specifying a target list (i.e. get distances to all other nodes in the graph), the algorithm runs as expected, assigning any unreachable nodes the max float64 value possible. Is it possible to change the behavior in the former case to assign unreachable nodes in the target list the max float64 value?

**Comment by fabratu** [comment]
Hi,

thanks for reaching out. We recently merged PR #984 addressing this problem. We will either put this in a bug-fix release or in the next scheduled release in November. However you can already use it by building and installing the master branch (or use a pre-built wheel from the most recent [CI-build](https://github.com/networkit/networkit/actions/runs/2954516998).)
